# Eval Feedback Review
Compare human reviewer scores/feedback against automated eval scorers, identify discrepancies, and suggest prompt improvements.

## Setup

In [1]:
from legal_rag.eval_review import EvalReviewClient
from config import *

import os
import pandas as pd

In [ ]:
EVAL_RESULTS_PATH = os.path.join(EVAL_RESULTS_ROOT_PATH, "Gemini-3.0 Flash Legal V02.json")
EVAL_RESULTS_PATH

'docs/KKP/LNC/eval_results/Gemini-3.0 Flash Legal V02.json'

## 1. Initialize Review Client

In [3]:
reviewer = EvalReviewClient(
    eval_model=EVAL_AI_MODEL,
    review_model=REVIEW_AI_MODEL,
    eval_prompt_version=EVAL_AI_PROMPT_VERSION,
    prompt_version=REVIEW_AI_PROMPT_VERSION,
)
reviewer

## 2. Load & Transform Eval Results JSON

In [ ]:
data = EvalReviewClient.load_eval_json(EVAL_RESULTS_PATH)

print(f"Loaded {len(data)} entries\n")
for i, d in enumerate(data):
    print(f"Entry {i+1}: {d['input'][:80]}...")
    print(f"  Auto:  {d['auto_scores']}")
    print(f"  Human: {d['human_scores']}")
    print("-------------------------------")

Loaded 5 entries

Entry 1: เจ้าของบัญชีเงินฝากถึงแก่กรรม บุคคลที่อ้างว่าเป็นทายาทขอดำเนินการจัดการบัญชี เช่...
  Auto:  {'reference': 0, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0}

Entry 2: นิติบุคคลเปิดบัญชีเงินฝาก ใช้หนังสือแสดงความประสงค์เปิดบัญชีแล้วลงนามโดยกรรมการผ...
  Auto:  {'reference': 0.5, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0.5}

Entry 3: เจ้าของบัญชีเงินฝากที่เสียชีวิตเป็นคนต่างชาติ ผู้ที่อ้างว่าเป็นทายาทมาขอถอนเงิน ...
  Auto:  {'reference': 0.5, 'judgement': 0.5, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 1, 'suggestion': 0.5}

Entry 4: ผู้เยาว์สามารถเปิดบัญชีเงินฝากกับธนาคารได้หรือไม่...
  Auto:  {'reference': 0.5, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 1}

Entry 5: กรณีลูกค้าขอเบิกถอนเงินฝากประจำ ธนาคารไม่ยินยอมให้ถอนก่อนครบกำหนดระยะเวลาฝากของล...
  Auto:  {'reference': 1, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 1, 'suggestion': 1}

In [5]:
# Quick score comparison table
rows = []
for i, d in enumerate(data):
    for key in ["reference", "judgement", "suggestion"]:
        rows.append({
            "entry": i + 1,
            "scorer": key,
            "auto_score": d["auto_scores"][key],
            "human_score": d["human_scores"][key],
            "diff": d["auto_scores"][key] - d["human_scores"][key],
        })

score_df = pd.DataFrame(rows)
score_df

    entry      scorer  auto_score  human_score  diff
0       1   reference         0.0          0.5  -0.5
1       1   judgement         0.0          0.5  -0.5
2       1  suggestion         0.0          0.0   0.0
3       2   reference         0.5          0.5   0.0
4       2   judgement         0.0          0.5  -0.5
5       2  suggestion         0.0          0.5  -0.5
6       3   reference         0.5          0.5   0.0
7       3   judgement         0.5          1.0  -0.5
8       3  suggestion         1.0          0.5   0.5
9       4   reference         0.5          0.0   0.5
10      4   judgement         1.0          0.0   1.0
11      4  suggestion         1.0          1.0   0.0
12      5   reference         1.0          0.5   0.5
13      5   judgement         1.0          1.0   0.0
14      5  suggestion         1.0          1.0   0.0

## 3. Re-run Scorers (with rationale capture)

In [5]:
reviews = reviewer.rerun_scorers(data)

/Users/rit/Documents/GitHub/Study RAG/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

  [1/5] reference: 0.5
  [1/5] judgement: 0.0
  [1/5] suggestion: 1.0
  [2/5] reference: 0.5
  [2/5] judgement: 0.0
  [2/5] suggestion: 0.0
  [3/5] reference: 0.5
  [3/5] judgement: 0.5
  [3/5] suggestion: 1.0
  [4/5] reference: 0.5
  [4/5] judgement: 1.0
  [4/5] suggestion: 0.5
  [5/5] reference: 1.0
  [5/5] judgement: 1.0
  [5/5] suggestion: 1.0

In [6]:
# Inspect re-run results for first entry
for sr in reviews[0].scorer_results:
    print(f"--- {sr.scorer_name} ---")
    print(f"Score: {sr.score}")
    print(f"Choice: {sr.choice}")
    print(f"Rationale: {sr.rationale[:300]}...")
    print()

--- reference ---
Score: 0.5
Choice: อ้างอิงมาตรากฎหมายถูกต้อง แต่ไม่ครอบคลุม มีมาตราสำคัญตกหล่น
Rationale: การประเมินเปรียบเทียบระหว่าง OUTPUT และ EXPECTED ในส่วนที่ 1 (มาตรากฎหมายที่เกี่ยวข้อง) มีรายละเอียดดังนี้:

1. **วิเคราะห์เฉลย (EXPECTED):** ระบุมาตราหลักคือ ป.พ.พ. มาตรา 1713 (เหตุในการตั้งผู้จัดการมรดก), 1718 (คุณสมบัติผู้จัดการมรดก), และ 1719 (สิทธิหน้าที่ผู้จัดการมรดก) ซึ่งเน้นไปที่กระบวนการตั้...

--- judgement ---
Score: 0.0
Choice: ไม่ถูกต้องตามเฉลย
Rationale: ผลการประเมินคือ 'ไม่ถูกต้องตามเฉลย' โดยมีเหตุผลประกอบดังนี้:

1. **ความขัดแย้งในผลทางกฎหมาย (Conclusion Mismatch):**
   - **เฉลย (EXPECTED):** วินิจฉัยว่าธนาคาร **ต้อง** อาศัยการดำเนินการของผู้จัดการมรดกตามคำสั่งศาลเท่านั้น เนื่องจากธนาคารไม่สามารถทราบได้ว่าทายาทที่มาติดต่อเป็นทายาททั้งหมดหรือไม่ เพ...

--- suggestion ---
Score: 1.0
Choice: ตอบได้ถูกต้อง ชัดเจน ครอบคลุม ให้ข้อเสนอแนะที่เป็นไปได้จริง
Rationale: คำตอบ (OUTPUT) มีความถูกต้อง ชัดเจน และครอบคลุมมากกว่าเฉลย (EXPECTED) โดยมีเหตุผลดังนี้:

1.  **ความถูกต้องทางกฎหมาย:** แม้เฉลยจะระบุว่า "ต้อง" เป็นผู้จัดการมรดกเท่านั้นเพื่อปิดความเสี่ยง แต่คำตอบได้อ้างอิงฎีกาที่ ๒๐๗๑/๒๕๖๓ และ ป.พ.พ. มาตรา ๖๖๕ ซึ่งเป็นหลักกฎหมายที่ถูกต้องและเป็นปัจจุบันกว่า โดยชี้แ...

In [7]:
# Compare re-run scores vs original auto scores vs human scores
rerun_rows = []
for review in reviews:
    for sr in review.scorer_results:
        rerun_rows.append({
            "entry": review.index + 1,
            "scorer": sr.scorer_name,
            "rerun_score": sr.score,
            "original_auto": review.auto_scores.get(sr.scorer_name, None),
            "human_score": review.human_scores.get(sr.scorer_name, None),
        })

rerun_df = pd.DataFrame(rerun_rows)
rerun_df

    entry      scorer  rerun_score  original_auto  human_score
0       1   reference          0.5            0.0          0.5
1       1   judgement          0.0            0.0          0.5
2       1  suggestion          1.0            0.0          0.0
3       2   reference          0.5            0.5          0.5
4       2   judgement          0.0            0.0          0.5
5       2  suggestion          0.0            0.0          0.5
6       3   reference          0.5            0.5          0.5
7       3   judgement          0.5            0.5          1.0
8       3  suggestion          1.0            1.0          0.5
9       4   reference          0.5            0.5          0.0
10      4   judgement          1.0            1.0          0.0
11      4  suggestion          0.5            1.0          1.0
12      5   reference          1.0            1.0          0.5
13      5   judgement          1.0            1.0          1.0
14      5  suggestion          1.0            1.0          1.0

## 4. Summarize Discrepancies (Human Feedback vs Auto Rationale)

In [8]:
reviews = reviewer.summarize_discrepancies(reviews)

  [1/5] Discrepancy summary done
  [2/5] Discrepancy summary done
  [3/5] Discrepancy summary done
  [4/5] Discrepancy summary done
  [5/5] Discrepancy summary done

In [9]:
# View discrepancy summary for each entry
for review in reviews:
    print(f"=== Entry {review.index + 1} ===")
    print(f"Q: {review.input[:100]}...")
    print(f"\nDiscrepancy Summary:\n{review.discrepancy_summary}")
    print("\n" + "="*80 + "\n")

=== Entry 1 ===
Q: เจ้าของบัญชีเงินฝากถึงแก่กรรม บุคคลที่อ้างว่าเป็นทายาทขอดำเนินการจัดการบัญชี เช่น ปิดบัญชีเงินฝากดัง...

Discrepancy Summary:
นี่คือบทสรุปการเปรียบเทียบการประเมินระหว่างผู้เชี่ยวชาญ (Human) และระบบอัตโนมัติ (AI) โดยจำแนกตามเกณฑ์ทั้ง 3 ด้านครับ

---

### 1. เกณฑ์ Reference (การอ้างอิงกฎหมาย)

**จุดที่เห็นตรงกัน:**
*   ทั้ง Human และ AI เห็นตรงกันว่า **"มาตราที่อ้างอิงไม่ครบถ้วน"** ตามธงคำตอบ (Expected)
*   ทั้งคู่ระบุว่า Output ขาดมาตราสำคัญเกี่ยวกับการตั้งผู้จัดการมรดก (เช่น ม.1713, 1718, 1719)

**จุดที่ขัดแย้งกัน:**
*   **ประเด็นการจัดรูปแบบ (Formatting):** Human ให้ความสำคัญกับ UX/UI โดยหักคะแนนเรื่องการจัดหน้าจอที่แสดงผลมาตราหลายวรรคติดกัน ทำให้ผู้อ่านสับสน ในขณะที่ AI ไม่ได้ตรวจจับหรือให้ความเห็นเรื่องรูปแบบการนำเสนอ (Format) มุ่งเน้นไปที่เนื้อหาเลขมาตราเพียงอย่างเดียว
*   **การให้คะแนน:** Human ให้คะแนน 0.5 (ให้ค่าความพยายามหรือความถูกต้องบางส่วน) แต่ AI ให้คะแนน 0 (ตัดคะแนนทั้งหมดเพราะขาดมาตราหลักในเฉลย)

**บทวิเคราะห์ความเหมาะสม:**
*   **Human ประเมินได้เหมาะสมกว่าในเชิงการใช้งานจริง** เพราะตระหนักถึงความถูกต้องของการนำเสนอ (Display) ซึ่งส่งผลต่อความเข้าใจของผู้ใช้ แต่ **AI แม่นยำกว่าในเชิงการเทียบเคียงเนื้อหา** เพราะสามารถระบุได้ชัดเจนว่า Output อ้างอิงมาตราถูกต้องในบริบทหนึ่ง (ม.665, 1599) แต่ไม่ตรงกับบริบทของเฉลย

---

### 2. เกณฑ์ Judgement (คำวินิจฉัย)

**จุดที่เห็นตรงกัน:**
*   ทั้ง Human และ AI เห็นตรงกันว่า **"ผลลัพธ์ของคำวินิจฉัยขัดแย้งกับเฉลย"** (Output บอกว่าไม่ต้องมีผู้จัดการมรดกก็ได้ แต่เฉลย/Human บอกว่าต้องมี)

**จุดที่ขัดแย้งกัน:**
*   **มุมมองการประเมิน:**
    *   **Human:** มองในมุม **"การบริหารความเสี่ยง (Risk Management)"** ของธนาคาร โดยมองว่าคำตอบของ Output นำไปสู่ความเสี่ยง จึงให้คะแนนน้อย (แต่ยังให้ 0.5)
    *   **AI:** มองในมุม **"ตรรกะและการเทียบเคียง (Logic & Matching)"** โดยระบุว่า Output ผิดเพราะผลทางกฎหมายตรงข้ามกับเฉลยโดยสิ้นเชิง (Conclusion Mismatch) จึงให้ 0
*   **การยอมรับเหตุผล:** Human ดูเหมือนจะไม่ยอมรับเหตุผลของ Output เลยเพราะห่วงเรื่องความเสี่ยง แต่ AI (ในส่วน Rationale) ยังพอจะรับรู้ได้ว่า Output อ้างอิงฎีกาและมีตรรกะของตัวเอง แต่ต้องตัดคะแนนเพราะโจทย์สั่งให้เทียบกับเฉลย

**บทวิเคราะห์ความเหมาะสม:**
*   **Human ประเมินได้เหมาะสมกว่าในบริบทธุรกิจ (Business Context)** เพราะคำแนะนำทางกฎหมายต้องคำนึงถึงความปลอดภัยขององค์กรเป็นหลัก แม้ทางทฤษฎีจะทำได้ แต่ทางปฏิบัติมีความเสี่ยง

---

### 3. เกณฑ์ Suggestion (ข้อเสนอแนะ)

**จุดที่เห็นตรงกัน:**
*   *(ไม่มีจุดที่เห็นตรงกันอย่างชัดเจน คะแนนเป็น 0 ทั้งคู่ แต่เหตุผลขัดแย้งกันอย่างรุนแรง)*

**จุดที่ขัดแย้งกัน:**
*   **ทิศทางของคำแนะนำ:**
    *   **Human:** ยืนยันกระต่ายขาเดียวว่า **"ต้องตั้งผู้จัดการมรดกเท่านั้น"** เพื่อปิดความเสี่ยง
    *   **AI (Rationale):** กลับมองว่า Output **"ทำได้ดีกว่าเฉลย (Better than Expected)"** โดย AI ให้เหตุผลว่า Output อ้างอิงคำพิพากษาฎีกา (ที่ 2071/2563) ซึ่งมีศักดิ์สูงกว่าระเบียบธนาคาร และมีข้อเสนอแนะที่ยืดหยุ่น (Indemnity Letter) ซึ่งเป็นไปได้จริง
*   **ความย้อนแย้งของระบบ AI:** แม้ Rationale ของ AI จะชมเชยว่า Output ถูกต้อง ชัดเจน และครอบคลุมกว่าเฉลย แต่คะแนน (Auto Score) กลับออกมาเป็น 0 (อาจเกิดจากการตั้งค่าระบบว่าถ้า Judgement ผิด Suggestion ต้องผิดตาม หรือเป็นข้อผิดพลาดของระบบให้คะแนนที่ไม่สอดคล้องกับ Rationale)

**บทวิเคราะห์ความเหมาะสม:**
*   **AI มี Rationale ที่เหนือกว่าในเชิงนิติศาสตร์ (Jurisprudence)** AI สามารถวิเคราะห์ได้ว่า "ระเบียบธนาคารจะยกเว้นบทบัญญัติแห่งกฎหมายและคำพิพากษาศาลฎีกามิได้" การที่ Output แนะนำทางออกโดยอ้างอิงฎีกา จึงเป็นคำตอบที่ "ถูกต้องตามกฎหมาย" มากกว่าเฉลยที่เน้น "Play Safe"
*   **Human ยึดติดกับธงคำตอบ/ระเบียบปฏิบัติ (Compliance)** มากเกินไป จนอาจละเลยข้อเท็จจริงทางกฎหมายที่ว่าทายาทมีสิทธิตามกฎหมายจริงๆ

---

### สรุปสาเหตุของความแตกต่างในคะแนน (Root Cause Analysis)

1.  **มุมมองที่ต่างกัน (Legal Rights vs. Risk Management):**
    *   **Output และ AI (Rationale)** ยึดหลัก **"สิทธิตามกฎหมายและคำพิพากษาศาลฎีกา"** (Legal Centric)
    *   **เฉลย (Reference) และ Human** ยึดหลัก **"นโยบายการบริหารความเสี่ยงของธนาคาร"** (Policy/Risk Centric)
    *   ความขัดแย้งนี้ทำให้คะแนนออกมาต่ำทั้งที่คำตอบของ Output มีคุณภาพสูงในเชิงกฎหมาย

2.  **ความเข้มงวดของระบบ (System Rigidity):**
    *   AI ถูกโปรแกรมให้เทียบกับเฉลย (Expected) เป็นหลัก แม้ AI จะฉลาดพอที่จะรู้ว่า Output มีเหตุผลดีกว่า (ดังที่ปรากฏใน Rationale ของ Suggestion) แต่ระบบอาจถูกล็อคให้กดคะแนนเป็น 0 หากผลลัพธ์ไม่ตรงกับเฉลย

3.  **เกณฑ์ UX/UI:**
    *   AI ยังขาดความสามารถในการประเมินความอ่านง่าย (Readability) ของตัวบทกฎหมาย ซึ่งเป็นสิ่งที่ Human ให้ความสำคัญ

================================================================================

=== Entry 2 ===
Q: นิติบุคคลเปิดบัญชีเงินฝาก ใช้หนังสือแสดงความประสงค์เปิดบัญชีแล้วลงนามโดยกรรมการผู้มีอำนาจลงนามตามหน้...

Discrepancy Summary:
นี่คือบทวิเคราะห์เปรียบเทียบระหว่างการให้คะแนนโดยผู้ตรวจสอบ (Human) และระบบอัตโนมัติ (AI) สำหรับคำถามเรื่องการใช้หนังสือแสดงความประสงค์แทนรายงานการประชุมในการเปิดบัญชีนิติบุคคล

---

### 1. เกณฑ์อ้างอิงหลักกฎหมาย (Reference)

**สถานะ:** **เห็นตรงกัน** (Human Score: 0.5 / Auto Score: 0.5)

*   **จุดที่เห็นตรงกัน:**
    *   ทั้งสองฝ่ายเห็นพ้องกันว่าคำตอบ **"ขาดมาตราสำคัญ"** นั่นคือ **ป.พ.พ. มาตรา 71** ซึ่งเป็นหัวใจสำคัญของเฉลย (เรื่องอำนาจกระทำการกรณีมีผู้แทนหลายคน)
    *   ทั้งสองฝ่ายให้คะแนนครึ่งหนึ่ง (0.5) ซึ่งแสดงว่ายอมรับว่ามีการอ้างอิงมาตราอื่นที่เกี่ยวข้องบ้าง (เช่น มาตรา 1144) แต่ยังไม่ครบถ้วนสมบูรณ์

*   **จุดที่แตกต่างกันในรายละเอียด:**
    *   **Human:** เน้นความละเอียดของตัวบทกฎหมายที่ยกมา เช่น การระบุข้อความไม่ครบวรรคในมาตรา 70
    *   **AI:** เน้นความ "เชื่อมโยงทางตรรกะ" ว่ามาตราที่ขาดไป (มาตรา 71) ส่งผลให้การวินิจฉัยผิดพลาด และมองว่ามาตราที่ยกมา (มาตรา 70) ไม่ตรงประเด็นเท่ากับเฉลย

*   **สรุป:** การประเมินสอดคล้องกัน AI สามารถระบุมาตราที่หายไปได้แม่นยำตรงกับสิ่งที่มนุษย์มองหา

---

### 2. เกณฑ์การวินิจฉัย (Judgement)

**สถานะ:** **ขัดแย้งกัน** (Human Score: 0.5 / Auto Score: 0)

*   **จุดที่ขัดแย้งกัน:**
    *   **Human (0.5):** มองว่าเป็นความ "บกพร่อง/ไม่ครบถ้วน" (Missing diagnosis) โดยระบุว่าขาดคำวินิจฉัยกรณีนิติบุคคลมีผู้แทนหลายคน แต่ยังให้คะแนนบางส่วน
    *   **AI (0):** มองว่าเป็นความ "ผิดพลาด/ขัดแย้ง" (Incorrect) โดยชี้ว่าเฉลยระบุว่า **"ทำไม่ได้"** (ถ้ามีผู้แทนหลายคนต้องใช้มติเสียงข้างมากตาม ม.71) แต่คำตอบระบุว่า **"ทำได้"** (โดยอ้างหลักตัวแทน) ซึ่งเป็นข้อสรุปที่ตรงกันข้าม

*   **ฝ่ายที่ประเมินได้เหมาะสมกว่า:** **AI (Auto Rationale)**
    *   **เหตุผล:** ในทางกฎหมายและการปฏิบัติงานธนาคาร หากเฉลยระบุว่า "ต้องใช้รายงานการประชุม (ทำไม่ได้หากใช้แค่หนังสือ)" แต่คำตอบบอกว่า "ใช้หนังสือได้" ถือเป็น **ความเสี่ยงทางกฎหมาย (Legal Risk)** ที่รุนแรง การให้คะแนน 0 ของ AI สะท้อนความถูกต้องของธงคำตอบมากกว่า เพราะคำตอบให้ผลลัพธ์ที่ผิดไปจากแนวปฏิบัติที่ต้องการ (Wrong Conclusion) ในขณะที่มนุษย์อาจจะใจดีให้คะแนนค่าวินิจฉัยในส่วนอื่นๆ ที่ถูกบ้าง

*   **สาเหตุของความแตกต่าง:** มนุษย์อาจให้คะแนนจาก "ความพยายามในการอ้างเหตุผล" หรือมองว่าคำตอบถูกต้องในกรณีทั่วไป (ผู้แทนคนเดียว) แต่ AI ตัดสินจาก "ข้อสรุปสุดท้าย (Final Verdict)" เทียบกับเฉลยอย่างเคร่งครัด

---

### 3. เกณฑ์ข้อเสนอแนะ (Suggestion)

**สถานะ:** **ขัดแย้งกัน** (Human Score: 0.5 / Auto Score: 0)

*   **จุดที่ขัดแย้งกัน:**
    *   **Human (0.5):** ให้คะแนนพร้อมเขียน Feedback แก้ไขว่า "ควรแสดงผลให้ require รายงานการประชุม" ซึ่งแสดงว่าคำตอบเดิมอาจจะไม่ได้แนะนำแบบนี้ หรือแนะนำไม่ชัดเจน แต่ยังให้คะแนนครึ่งหนึ่ง
    *   **AI (0):** ให้ศูนย์คะแนน เพราะเมื่อคำวินิจฉัยผิด (บอกว่าทำได้) ข้อเสนอแนะย่อมผิดตามไปด้วย (ขัดแย้งกับเฉลยที่ต้องการให้ปฏิเสธหนังสือแสดงความประสงค์หากหลักฐานไม่พอ)

*   **ฝ่ายที่ประเมินได้เหมาะสมกว่า:** **AI (Auto Rationale)**
    *   **เหตุผล:** หากคำตอบแนะนำสิ่งที่ขัดแย้งกับนโยบาย (เช่น แนะนำว่าใช้หนังสือแสดงความประสงค์ได้ ทั้งที่ธนาคารต้องการรายงานการประชุมเพื่อยืนยันมติเสียงข้างมาก) ถือเป็นคำแนะนำที่นำไปสู่การปฏิบัติงานที่ผิดพลาด AI จึงตัดสินได้ถูกต้องตามตรรกะว่า "ไม่ถูกต้องตามเฉลย"

*   **สาเหตุของความแตกต่าง:** ผู้ตรวจสอบ (Human) อาจมองเห็นว่ามีส่วนที่พอใช้ได้หรืออาจจะให้คะแนนเพราะคำตอบมีการเขียนแนวทางปฏิบัติมาบ้าง (แม้จะไม่ถูกต้อง 100%) แต่ AI ยึดตามความปลอดภัยและความถูกต้องของคำแนะนำเป็นหลัก (Safety & Accuracy)

---

### บทสรุปภาพรวม

1.  **ความแม่นยำ:** AI มีความแม่นยำสูงในการจับประเด็น "ข้อขัดแย้ง" (Contradiction) ระหว่างคำตอบกับเฉลย โดยเฉพาะเรื่อง "ทำได้ vs ทำไม่ได้"
2.  **ความเข้มงวด:** AI มีความเข้มงวดกว่ามนุษย์ (Strict) ในเกณฑ์ Judgement และ Suggestion หากผลลัพธ์ทางกฎหมายผิด AI จะตัดคะแนนทั้งหมดทันที ในขณะที่มนุษย์มีแนวโน้มให้คะแนนแบบ Partial Credit (ให้คะแนนบางส่วน) แม้ข้อสรุปจะคลาดเคลื่อน
3.  **คำแนะนำ:** ในกรณีนี้ การประเมินของ AI น่าเชื่อถือกว่าในแง่ของการควบคุมความเสี่ยง (Risk Control) เพราะการตอบว่า "ใช้หนังสือแทนรายงานการประชุมได้" ในกรณีที่กฎหมาย (ตามเฉลย) บังคับเรื่องเสียงข้างมาก อาจก่อให้เกิดความเสียหายต่อธนาคารได้ คะแนน 0 จึงเหมาะสมกว่า 0.5

================================================================================

=== Entry 3 ===
Q: เจ้าของบัญชีเงินฝากที่เสียชีวิตเป็นคนต่างชาติ ผู้ที่อ้างว่าเป็นทายาทมาขอถอนเงิน ปิดบัญชีได้หรือไม่ โ...

Discrepancy Summary:
นี่คือการเปรียบเทียบและวิเคราะห์ผลการประเมินระหว่างผู้ตรวจสอบ (Human) และระบบอัตโนมัติ (AI) สำหรับโจทย์ทางกฎหมายดังกล่าว

---

### 1. เกณฑ์: Reference (มาตรากฎหมายที่เกี่ยวข้อง)

**1. จุดที่เห็นตรงกัน**
*   **คะแนน:** ทั้ง Human และ AI ให้คะแนนเท่ากันที่ **0.5**
*   **ประเด็นหลัก:** ทั้งสองฝ่ายเห็นตรงกันว่า "มาตรากฎหมายไม่ครบถ้วน" ตามเฉลย

**2. จุดที่ขัดแย้งกันและบทวิเคราะห์**
*   **ความแตกต่าง:**
    *   **Human:** เน้นเรื่องรูปแบบการแสดงผล (UX) ว่ามาตราที่มีหลายวรรคถูกนำมารวมกัน ไม่แยกบรรทัด ทำให้เข้าใจผิด และระบุภาพรวมว่ามาตราไม่ครบ
    *   **AI:** ระบุเจาะจงได้ชัดเจนว่าขาดมาตราใดที่เป็นสาระสำคัญ (ป.วิ.พ. มาตรา 4 จัตวา) และระบุว่ามีมาตราใดที่เกินมาแต่ไม่สำคัญ
*   **ฝ่ายที่ประเมินได้เหมาะสมกว่า:** **AI**
    *   **เหตุผล:** AI สามารถระบุเนื้อหาทางกฎหมายที่ขาดหายไปได้แม่นยำกว่า (Specific content gap) ซึ่งเป็นหัวใจสำคัญของการให้คะแนนความถูกต้องของ Reference ส่วน Human เน้นเรื่องการจัดรูปแบบ (Formatting) ซึ่งสำคัญแต่เป็นเรื่องรองในเชิงความถูกต้องของกฎหมาย

**3. สาเหตุของความแตกต่าง**
*   Human ให้ความสำคัญกับความยากง่ายในการอ่าน (Readability) ในขณะที่ AI ตรวจสอบความครบถ้วนของเนื้อหา (Completeness) เทียบกับเฉลย

---

### 2. เกณฑ์: Judgement (การวินิจฉัย)

**1. จุดที่เห็นตรงกัน**
*   ไม่มีจุดที่เห็นตรงกันในเรื่องคะแนน (Human ให้ 1, AI ให้ 0.5)

**2. จุดที่ขัดแย้งกันและบทวิเคราะห์**
*   **ความแตกต่าง:**
    *   **Human:** ให้คะแนนเต็ม **1** แต่ในช่อง Feedback กลับเขียนข้อบกพร่องเรื่องการจัดรูปแบบมาตรา (ซ้ำกับ Reference) และเขียนเรื่องข้อเสนอแนะเกี่ยวกับอัยการ (ซึ่งควรอยู่ในส่วน Suggestion)
    *   **AI:** ให้คะแนน **0.5** โดยให้เหตุผลว่า แม้ผลทางกฎหมายถูกต้อง (จ่ายเงินไม่ได้) แต่ขาดการอ้างอิงเรื่องเขตอำนาจศาล (ป.วิ.พ. 4 จัตวา) และขาดรายละเอียดเรื่องสำนักงานอัยการฯ ซึ่งระบุไว้ในเฉลย
*   **ฝ่ายที่ประเมินได้เหมาะสมกว่า:** **AI**
    *   **เหตุผล:** การประเมินของ Human มีความขัดแย้งกันเอง (Inconsistent) คือให้คะแนนเต็มแต่คอมเมนต์ระบุข้อผิดพลาด และดูเหมือน Human จะนำ Feedback ของส่วนอื่นมาใส่ผิดช่อง ในขณะที่ AI วิเคราะห์ได้ตรงจุดว่า การขาดประเด็นเรื่อง "เขตอำนาจศาล" และ "ช่องทางช่วยเหลือทายาท (อัยการ)" ทำให้การวินิจฉัยไม่สมบูรณ์ตามเฉลย จึงตัดคะแนนถูกต้องแล้ว

**3. สาเหตุของความแตกต่าง**
*   Human Error: ผู้ตรวจสอบน่าจะสับสนหรือวางข้อความ Feedback ผิดช่อง และอาจเผลอกดให้คะแนนเต็มโดยไม่ได้พิจารณาองค์ประกอบที่ขาดหายไปอย่างถี่ถ้วน
*   AI ยึดตามเฉลย (Expected Output) อย่างเคร่งครัด เมื่อพบว่าเนื้อหาไม่ครบตาม Key Points จึงตัดคะแนน

---

### 3. เกณฑ์: Suggestion (ข้อสรุปและข้อเสนอแนะ)

**1. จุดที่เห็นตรงกัน**
*   ไม่มีจุดที่เห็นตรงกันในเรื่องคะแนน (Human ให้ 0.5, AI ให้ 1)

**2. จุดที่ขัดแย้งกันและบทวิเคราะห์**
*   **ความแตกต่าง:**
    *   **Human:** ให้คะแนน **0.5** โดยมองว่าคำตอบขาดคำแนะนำสำคัญเรื่อง "สำนักงานอัยการพิเศษฝ่ายคุ้มครองสิทธิประชาชนระหว่างประเทศ" ซึ่งเป็นช่องทางอำนวยความสะดวกให้ทายาท
    *   **AI:** ให้คะแนนเต็ม **1** โดยมองว่าคำตอบนั้นถูกต้อง ชัดเจน และนำไปปฏิบัติได้จริง (Actionable) แล้ว (คือแนะนำให้ไปร้องต่อศาล) โดยมองว่าเรื่องอัยการเป็นส่วนเสริม ไม่ใช่สาระสำคัญที่สุดที่จะทำให้เสียคะแนน
*   **ฝ่ายที่ประเมินได้เหมาะสมกว่า:** **Human**
    *   **เหตุผล:** ในบริบทของการให้บริการ (Service Mind) หรือการแก้ปัญหาให้ลูกค้าธนาคาร การแนะนำช่องทางที่ "ไม่มีค่าใช้จ่าย" (สำนักงานอัยการ) ตามที่เฉลยระบุถือเป็น *Value Added* ที่สำคัญมาก หากเฉลยระบุไว้ การที่ระบบตอบเพียงแค่ "ให้ไปศาล" (ซึ่งลูกค้ารู้สึกยุ่งยากและเสียเงิน) ถือว่ายังไม่สมบูรณ์แบบที่สุด Human จึงตัดสินถูกแล้วที่ตัดคะแนนในส่วนนี้

**3. สาเหตุของความแตกต่าง**
*   AI ตีความคำว่า "ข้อเสนอแนะที่เป็นไปได้จริง" กว้างเกินไป โดยมองว่าแค่บอกให้ไปศาลก็ถูกต้องตามกฎหมายแล้ว แต่ไม่ได้คำนึงถึงบริบทความช่วยเหลือหรือ Best Practice ที่ระบุไว้ในเฉลยอย่างละเอียดเท่ามนุษย์

---

### สรุปภาพรวม
*   **Reference:** AI ทำงานได้ดีกว่าในการระบุมาตราที่หายไป
*   **Judgement:** AI ทำงานได้ดีกว่ามาก เพราะ Human ให้คะแนนขัดแย้งกับคอมเมนต์ตัวเอง
*   **Suggestion:** Human ตัดสินได้ดีกว่า เพราะเล็งเห็นถึงความสำคัญของคำแนะนำเฉพาะเจาะจง (เรื่องอัยการ) ที่เป็นประโยชน์ต่อผู้ใช้บริการมากกว่าแค่ข้อกฎหมายกว้างๆ

================================================================================

=== Entry 4 ===
Q: ผู้เยาว์สามารถเปิดบัญชีเงินฝากกับธนาคารได้หรือไม่...

Discrepancy Summary:
นี่คือการวิเคราะห์เปรียบเทียบระหว่างการประเมินโดยมนุษย์ (Human) และระบบอัตโนมัติ (AI) ในแต่ละเกณฑ์ สำหรับคำถามกฎหมายเรื่อง "ผู้เยาว์เปิดบัญชีเงินฝาก"

---

### 1. เกณฑ์ Reference (มาตรากฎหมายที่เกี่ยวข้อง)

*   **คะแนน:** Human (0) vs AI (0.5)
*   **จุดที่เห็นตรงกัน:**
    *   ทั้งสองฝ่ายเห็นตรงกันว่าคำตอบของ AI (Output) มีการอ้างอิงมาตราที่ "เกินความจำเป็น" หรือไม่เกี่ยวข้อง (Human: มีมาตราที่ไม่เกี่ยวข้อง, AI: ระบุมาตรา 22, 1574 ซึ่งไม่อยู่ในเฉลย)
    *   ทั้งสองฝ่ายเห็นตรงกันว่ามีมาตราสำคัญที่ "ขาดหายไป" (Human: เกี่ยวข้องไม่ครบ, AI: ขาดมาตรา 19, 175, 1566)
*   **จุดที่ขัดแย้งกัน:**
    *   **การให้คะแนน:** Human ให้ 0 (ตก) ในขณะที่ AI ให้ 0.5 (พอใช้)
    *   **ฝ่ายที่ประเมินได้เหมาะสมกว่า:** **AI (Auto)**
    *   **เหตุผล:** แม้คำตอบจะไม่สมบูรณ์ แต่คำตอบได้อ้างอิง "หัวใจสำคัญ" ของเรื่องนี้คือ **มาตรา 21** (หลักทั่วไป: ต้องได้รับความยินยอม) และ **มาตรา 24** (ข้อยกเว้น: สมแก่ฐานานุรูป) ซึ่งเป็นแกนหลักในการตอบคำถามนี้ การที่ Human ให้ 0 เลยอาจดูเคร่งครัดเกินไป เพราะผู้ตอบยังระบุมาตราหลักได้ถูกต้อง ส่วนมาตราที่ขาด (เช่น 19 นิยามผู้เยาว์) เป็นมาตราประกอบ
*   **สาเหตุของความแตกต่าง:** Human อาจใช้เกณฑ์ "All or Nothing" (ถ้ามีส่วนเกินหรือขาดส่วนสำคัญ = 0) ในขณะที่ AI มี Logic ในการให้คะแนนบางส่วน (Partial Credit) เมื่อพบ Key Sections ที่ถูกต้อง

---

### 2. เกณฑ์ Judgement (คำวินิจฉัย)

*   **คะแนน:** Human (0) vs AI (1)
*   **จุดที่เห็นตรงกัน:** ไม่มี
*   **จุดที่ขัดแย้งกัน:**
    *   **ความถูกต้องของการปรับบทกฎหมาย:** Human ระบุว่า "คำวินิจฉัยในส่วนข้อยกเว้นไม่ถูกต้อง" ในขณะที่ AI มองว่า "อ้างอิงถูกต้อง อธิบายข้อยกเว้นชัดเจน และผลทางกฎหมายถูกต้อง"
    *   **ฝ่ายที่ประเมินได้เหมาะสมกว่า:** **Human (ผู้เชี่ยวชาญ)**
    *   **เหตุผล:** ในทางปฏิบัติและแนวคำพิพากษา การ "เปิดบัญชีธนาคาร" ของผู้เยาว์ มัก **ไม่ถูกจัดว่าเป็นนิติกรรมที่เป็นไปตามมาตรา 24** (การที่ต้องทำเองเฉพาะตัวหรือสมแก่ฐานานุรูปฯ) โดยอัตโนมัติ ธนาคารมักมองว่าเป็นนิติกรรมที่ต้องได้รับความยินยอม (ม.21) เว้นแต่จะมีกฎหมายเฉพาะหรืออายุถึงเกณฑ์ (เช่น 15 ปี)
    *   การที่ AI ให้คะแนนเต็มเพราะ AI ตรวจจับแค่ว่า "มีการอ้าง Logic: หลักการ -> ข้อยกเว้น" (Structure Matching) แต่ AI ไม่มีความรู้ลึกซึ้ง (Domain Knowledge) พอที่จะตัดสินว่า การนำมาตรา 24 มาจับกับการเปิดบัญชีนั้น "สมเหตุสมผลในทางกฎหมายหรือไม่" AI จึงถูกหลอกด้วยโครงสร้างคำตอบที่ดูดีแต่เนื้อหาผิด
*   **สาเหตุของความแตกต่าง:** AI ตรวจสอบจาก Keywords และความสอดคล้องกับเฉลยในเชิงโครงสร้าง (มีมาตรา 24 เหมือนเฉลย) แต่ Human ตรวจสอบที่ "ความถูกต้องของการตีความกฎหมาย" (Legal Interpretation) ซึ่งคำตอบของผู้เรียนอาจจะอ้าง ม.24 ผิดบริบท

---

### 3. เกณฑ์ Suggestion (ข้อสรุปและข้อเสนอแนะ)

*   **คะแนน:** Human (1) vs AI (1) (หมายเหตุ: Choice ของ AI ระบุว่า "ไม่ครอบคลุม" แต่คะแนนระบุ 1 ซึ่งอาจเป็นความย้อนแย้งในระบบ หรือเป็นการปัดเศษขึ้น)
*   **จุดที่เห็นตรงกัน:**
    *   ทั้งคู่ให้คะแนนในเกณฑ์สูง (1) แสดงว่ายอมรับในผลลัพธ์สุดท้าย
*   **จุดที่ขัดแย้งกัน:**
    *   **เนื้อหาข้อเสนอแนะ:**
        *   **Human:** มองว่าคำตอบ "เยิ่นเย้อเกินไป" (อยากให้ตัดข้อ 4 ออก) แต่เนื้อหาหลักถูกต้องแล้ว
        *   **AI:** มองว่าคำตอบ "ขาดเนื้อหาสำคัญ" (เรื่องเกณฑ์อายุ 15 ปี) และมีความเข้มงวดเกินไป (Conservative) เมื่อเทียบกับเฉลย
    *   **ฝ่ายที่ประเมินได้เหมาะสมกว่า:** **กึ่งๆ กัน (Mixed)**
    *   **เหตุผล:**
        *   **Human** มองในมุมความ "กระชับและได้ใจความ" (Practicality) คือแนะนำธนาคารได้ปลอดภัย
        *   **AI** มองในมุม "ความครบถ้วนตามเฉลย" (Accuracy vs Reference) คือคำตอบขาดประเด็นเรื่องอายุ 15 ปี ซึ่งเป็นเกณฑ์ปฏิบัติจริงของธนาคารพาณิชย์
*   **สาเหตุของความแตกต่าง:** Human เน้นความ Clean ของคำตอบ (ตัดส่วนเกิน) ส่วน AI เน้นการ Match กับ Information Points ในเฉลย (ต้องมีเรื่องอายุ 15 ปี) แต่สุดท้ายทั้งคู่ให้คะแนนผ่านเหมือนกัน เพราะถือว่าเป็นคำแนะนำที่ใช้งานได้

---

### สรุปภาพรวม
*   **ปัญหาใหญ่ที่สุด:** อยู่ที่เกณฑ์ **Judgement** ซึ่ง AI ให้คะแนนเต็ม (1) ในขณะที่ Human ให้ตก (0) นี่คือ **Critical Error ของ AI** ที่ไม่สามารถตรวจสอบความถูกต้องของการปรับบทกฎหมาย (Application of Law) ได้อย่างลึกซึ้ง ตรวจจับได้เพียงการอ้างอิงเลขมาตราที่ตรงกันเท่านั้น
*   **แนวทางปรับปรุง:** AI จำเป็นต้องได้รับการเทรนเพิ่มในเรื่อง "บริบทของข้อยกเว้น (ม.24)" ว่าใช้กับกรณีเปิดบัญชีได้หรือไม่ ไม่ใช่ดูแค่ว่ามีการกล่าวถึงมาตรานั้นๆ

================================================================================

=== Entry 5 ===
Q: กรณีลูกค้าขอเบิกถอนเงินฝากประจำ ธนาคารไม่ยินยอมให้ถอนก่อนครบกำหนดระยะเวลาฝากของลูกค้า ธนาคารต้องรับผ...

Discrepancy Summary:
นี่คือบทสรุปการเปรียบเทียบระหว่างการประเมินของมนุษย์ (Human) และระบบอัตโนมัติ (AI) สำหรับคำตอบทางกฎหมายดังกล่าว

---

### 1. เกณฑ์: Reference (การอ้างอิงกฎหมาย)

**จุดที่เห็นตรงกัน:**
*   ทั้ง Human และ AI ยอมรับว่า Output มีการระบุ "ตัวบทกฎหมาย" เข้ามาในคำตอบ (มาตรา 672 และ 673)

**จุดที่ขัดแย้งกัน:**
*   **คะแนน:** Human ให้ 0.5 (ครึ่งเดียว) ในขณะที่ AI ให้ 1 (เต็ม)
*   **เหตุผล:** Human หักคะแนนเนื่องจากปัญหาเรื่อง **"รูปแบบการแสดงผล"** (Format) ที่ตัวบทแบ่งเป็น 2 วรรคแต่แสดงผลรวมเป็นวรรคเดียว ในขณะที่ AI ให้คะแนนเต็มเพราะมองที่ **"เนื้อหา"** (Content) ว่าระบุเลขมาตราได้ถูกต้องและครอบคลุมตามเฉลย รวมถึงมีมาตราเสริมที่เกี่ยวข้อง

**ฝ่ายที่ประเมินได้เหมาะสมกว่า:**
*   **AI ประเมินได้เหมาะสมกว่าในบริบทของการวัดความรู้กฎหมาย** เพราะสาระสำคัญคือการอ้างอิงเลขมาตราและหลักกฎหมายที่ถูกต้องเพื่อแก้ปัญหา การที่วรรคถูกรวมกันอาจเป็นปัญหาทางเทคนิคของการแสดงผลหรือการจัดรูปแบบ ซึ่งไม่ได้ทำให้ความหมายทางกฎหมายผิดเพี้ยนไปจนถึงขั้นต้องหักคะแนนถึง 50%

**สาเหตุที่เป็นไปได้ของความแตกต่าง:**
*   Human ให้ความสำคัญกับความถูกต้องของ "รูปแบบตัวบท" (Literal/Formatting accuracy) อย่างเคร่งครัด
*   AI มุ่งเน้นการจับคู่ Keyword และความสัมพันธ์ของมาตรากฎหมาย (Semantic/Content accuracy) โดยไม่ได้ถูกตั้งโปรแกรมให้ตรวจสอบการเว้นวรรคบรรทัดของตัวบท

---

### 2. เกณฑ์: Judgement (การวินิจฉัย)

**จุดที่เห็นตรงกัน:**
*   **คะแนน:** ทั้ง Human และ AI ให้คะแนนเต็ม (1) เหมือนกัน

**จุดที่ขัดแย้งกัน:**
*   **คำอธิบาย:** AI อธิบายเหตุผลที่ให้คะแนนโดยละเอียดว่าคำตอบวินิจฉัยถูกต้องตามหลักกฎหมาย (ธนาคารปฏิเสธได้ตาม ม.673) และเชื่อมโยงเหตุผลได้ดี แต่ Human กลับเขียน Feedback เหมือนเดิมเป๊ะกับข้อ Reference ("ตัวบทแบ่งเป็น 2 วรรค...") ซึ่งไม่เกี่ยวข้องกับเกณฑ์การวินิจฉัย

**ฝ่ายที่ประเมินได้เหมาะสมกว่า:**
*   **AI ให้ Rationale ที่เหมาะสมกว่า** เพราะอธิบายถึงตรรกะทางกฎหมายและการปรับใช้กฎหมายกับข้อเท็จจริง ในขณะที่ Human ดูเหมือนจะคัดลอกข้อความ (Copy-Paste) จากช่องก่อนหน้ามาใส่ หรืออาจจะ Comment ภาพรวมทิ้งไว้จุดเดียวแต่ไม่ได้แก้ข้อความให้ตรงกับเกณฑ์

**สาเหตุที่เป็นไปได้ของความแตกต่าง:**
*   Human อาจเกิดความผิดพลาดในการกรอกข้อมูล (Human Error) หรือใช้ Feedback เดียวตอบทุกช่อง แต่ตัดสินใจให้คะแนนเต็มในส่วนนี้เพราะถือว่าผลลัพธ์การวินิจฉัยถูก แม้รูปแบบตัวบทจะผิด

---

### 3. เกณฑ์: Suggestion (ข้อเสนอแนะ)

**จุดที่เห็นตรงกัน:**
*   **คะแนน:** ทั้ง Human และ AI ให้คะแนนเต็ม (1) เหมือนกัน

**จุดที่ขัดแย้งกัน:**
*   **คำอธิบาย:** เช่นเดียวกับเกณฑ์ Judgement AI วิเคราะห์เนื้อหาข้อเสนอแนะว่าตรงกับเงื่อนไขผลิตภัณฑ์ (Terms & Conditions) และมีความเป็นไปได้จริง แต่ Human ยังคงใช้ Feedback เดิมเรื่อง "การแบ่งวรรคของตัวบท"

**ฝ่ายที่ประเมินได้เหมาะสมกว่า:**
*   **AI ประเมินได้เหมาะสมกว่า** เพราะมีการตรวจสอบเนื้อหาข้อเสนอแนะว่าสอดคล้องกับแนวปฏิบัติจริงของธนาคารและตรงกับเฉลย ส่วน Human ไม่ได้กล่าวถึงเนื้อหาของข้อเสนอแนะเลยใน Feedback

**สาเหตุที่เป็นไปได้ของความแตกต่าง:**

## 5. Analyze Score Differences (Overall)

In [10]:
analysis = reviewer.analyze_score_differences(reviews)
print(analysis)

นี่คือรายงานการวิเคราะห์คุณภาพระบบประเมินผลอัตโนมัติ (Auto Evaluation) สำหรับ RAG ทางกฎหมาย โดยเปรียบเทียบกับผู้เชี่ยวชาญ (Human) จากข้อมูล 5 กรณีศึกษาข้างต้น

---

# รายงานวิเคราะห์คุณภาพระบบประเมินผลอัตโนมัติ (AI vs Human)

## 1. อัตราความสอดคล้องรายเกณฑ์ (Consistency Analysis)

จากการวิเคราะห์ข้อมูลทั้ง 5 Entry พบว่าความสอดคล้องของคะแนนระหว่าง AI และ Human มีลักษณะดังนี้:

*   **เกณฑ์ Reference (การอ้างอิง):** **ความสอดคล้องระดับปานกลาง**
    *   คะแนนมักไปในทิศทางเดียวกันในกรณีที่ "มาตราขาดหายไป"
    *   *ความต่าง:* AI แม่นยำเรื่องเนื้อหา (Content) ว่ามาตราใดขาด/เกิน ในขณะที่ Human ให้ความสำคัญกับรูปแบบการจัดวาง (Formatting/UX) มากจนบางครั้งบดบังความถูกต้องของเนื้อหา (เช่น Entry 5 ที่ Human หักคะแนนเพราะการเว้นวรรคผิด)
*   **เกณฑ์ Judgement (การวินิจฉัย):** **ความสอดคล้องระดับต่ำ (Critical Divergence)**
    *   เป็นเกณฑ์ที่มีความขัดแย้งสูงที่สุด AI มักตัดสินแบบ "ขาว/ดำ" (Binary) คือถ้าธงคำตอบผิด = 0 ทันที (Entry 1, 2) ในขณะที่ Human มีการให้คะแนนบางส่วน (Partial Credit)
    *   *จุดอันตราย:* AI ให้คะแนนเต็มในกรณีที่ "โครงสร้างดูดีแต่ผิดหลักกฎหมาย" (Entry 4) ซึ่ง Human ให้ 0
*   **เกณฑ์ Suggestion (ข้อเสนอแนะ):** **ความสอดคล้องระดับต่ำ**
    *   AI มักให้คะแนนตามผลของ Judgement (Chained Logic) หรือดูแค่ความเป็นไปได้ทางทฤษฎี (Actionable)
    *   Human ให้คะแนนโดยคำนึงถึง "ความเหมาะสมทางธุรกิจ/การบริการ" (Service Mind & Business Context) เช่น การแนะนำอัยการ (ฟรี) ดีกว่าแนะนำไปฟ้องศาล (เสียเงิน) ใน Entry 3

## 2. แนวโน้มอคติเชิงระบบ (Systematic Bias)

### 2.1 AI Bias (อคติของระบบอัตโนมัติ)
*   **Strictness on Conclusion (เข้มงวดกับผลลัพธ์ปลายทาง):** หากบทสรุป (Yes/No) ขัดแย้งกับเฉลย AI มีแนวโน้มจะให้ 0 ทันที โดยไม่พิจารณาตรรกะสนับสนุนที่อาจจะมีน้ำหนักในทางนิติศาสตร์ (Entry 1, 2)
*   **Structure over Substance (โครงสร้างสำคัญกว่าเนื้อหา):** AI มีแนวโน้มให้คะแนนสูง (Over-scoring) หาก Output มีโครงสร้างตรรกะครบ (หลักการ -> เหตุผล -> สรุป) และมี Keyword ตรงกับเฉลย แม้ว่าการปรับบทกฎหมายจะผิดเพี้ยนไปจากความเป็นจริง (Entry 4)
*   **Ignorance of UX:** AI ไม่นำปัจจัยเรื่องความอ่านง่าย (Readability) มาคำนวณคะแนนเลย

### 2.2 Human Bias (อคติของผู้ตรวจมนุษย์)
*   **Formatting Bias:** ผู้ตรวจสอบมนุษย์มีแนวโน้มหักคะแนนรุนแรงหากการจัดรูปแบบตัวบทกฎหมายทำให้อ่านยาก แม้เนื้อหาจะถูก 100% (Entry 1, 3, 5)
*   **Inconsistency (ความไม่สม่ำเสมอ):** พบกรณี Human Error เช่น การให้คะแนนเต็มแต่คอมเมนต์ตำหนิ หรือการ Copy-Paste คอมเมนต์เดิมมาใส่ในช่องที่ไม่เกี่ยวข้อง (Entry 5)
*   **Policy Oriented:** ยึดติดกับระเบียบธนาคารมากกว่าหลักกฎหมายทั่วไป (Entry 1)

## 3. ประเภทกรณีที่มีความขัดแย้งสูง

1.  **กรณี "คำตอบถูกกฎหมาย แต่ผิดระเบียบธนาคาร" (Entry 1):**
    *   AI (Rationale) มองว่าทำได้ตามฎีกา / Human มองว่าห้ามทำตามระเบียบ
    *   *ผลลัพธ์:* AI อาจให้เหตุผลดีแต่คะแนนตก หรือ Human ให้คะแนนน้อยเพื่อกันความเสี่ยง
2.  **กรณี "คำตอบมีโครงสร้างถูกต้อง แต่ผิดหลักปฏิบัติจริง" (Entry 4 - False Positive):**
    *   นี่คือกรณีที่ **อันตรายที่สุด** AI ให้คะแนนเต็มเพราะคำตอบอ้างมาตราตรงกับเฉลยและมีตรรกะ แต่ Human รู้ว่าในทางปฏิบัติมาตรานั้น (ม.24) ไม่ใช้กับการเปิดบัญชี
3.  **กรณี "ขาด Service Mind" (Entry 3):**
    *   AI มองว่าการแนะนำให้ "ไปฟ้องศาล" เป็นคำแนะนำที่ถูกต้องและจบแล้ว แต่ Human มองว่า "แย่" เพราะไม่ได้แนะนำทางเลือกที่ประหยัดกว่า (อัยการ) ตามเฉลย

## 4. สมมติฐานสาเหตุและข้อเสนอแนะ

### สาเหตุหลักของความแตกต่าง
1.  **ข้อจำกัดของ Prompt:** Prompt ปัจจุบันน่าจะเน้นสั่งให้ AI "เปรียบเทียบความเหมือนกับเฉลย" (Similarity/Matching) มากกว่าการ "ตรวจสอบความถูกต้องทางกฎหมาย" (Legal Validity Check) ทำให้ AI ให้คะแนนผิดเมื่อเจอคำตอบที่เขียนดีแต่ผิดหลัก (Entry 4) หรือคำตอบที่ดีกว่าเฉลย (Entry 1)
2.  **Lack of Context:** AI ขาดความเข้าใจบริบท "การบริหารความเสี่ยง" และ "งานบริการลูกค้า" ของธนาคาร ทำให้ตัดสินใจพลาดในเกณฑ์ Suggestion
3.  **Human Factors:** ผู้ตรวจสอบให้ความสำคัญกับ UI/UX ปนกับความถูกต้องของเนื้อหา

### ข้อเสนอแนะเพื่อปรับปรุง (Recommendations)

1.  **ปรับจูน Prompt สำหรับ Judgement:** เพิ่มคำสั่งให้ AI ตรวจสอบ "การปรับบทกฎหมายที่ผิดพลาด" (Misapplication of Law) โดยเฉพาะ ไม่ใช่แค่ตรวจการมีอยู่ของเลขมาตรา เพื่อแก้ปัญหา Entry 4
2.  **แยกเกณฑ์การประเมิน Format:** ควรแยกหัวข้อ UX/Formatting ออกจาก Reference เพื่อไม่ให้คะแนนเนื้อหาถูกบิดเบือนจากรูปแบบการแสดงผล (แก้ปัญหา Human Bias)
3.  **เพิ่ม Criteria "Risk & Policy":** เพิ่มเกณฑ์การให้คะแนนด้าน "ความสอดคล้องกับนโยบาย/ความเสี่ยง" แยกต่างหาก เพื่อให้ AI เข้าใจว่าคำตอบที่ถูกกฎหมายแต่อาจสร้างความเสี่ยงให้ธนาคารควรได้คะแนนน้อยในส่วนนี้ (แก้ปัญหา Entry 1, 2)
4.  **ปรับปรุงเฉลย (Refine Ground Truth):** เฉลยควรระบุชัดเจนว่า "Key Point" ใดที่ *ต้องมี* (Must have) และ *ควรมี* (Nice to have) เช่น กรณี Entry 3 เรื่องอัยการ เพื่อให้ AI ให้คะแนนน้ำหนักได้ถูกต้อง

## 6. Suggest Prompt Edits per Scorer

In [11]:
ref_suggestions = reviewer.suggest_prompt_edits(reviews, "reference")
print(ref_suggestions)

จากการวิเคราะห์ข้อมูลเปรียบเทียบระหว่างคะแนนจากระบบ (Auto) และคะแนนจากมนุษย์ (Human) ทั้ง 5 รายการ พบความแตกต่างที่มีนัยสำคัญในเรื่อง "เกณฑ์การให้คะแนน" โดยเฉพาะมิติด้านรูปแบบ (Formatting) และความเคร่งครัดในการอ้างอิงข้อกฎหมายที่ไม่เกี่ยวข้อง นี่คือข้อเสนอแนะในการปรับปรุง Prompt ครับ

---

## 1. สรุปปัญหาที่พบ (Summary of Problems)

1.  **AI มองข้ามเรื่องการจัดรูปแบบ (Formatting Blindness):** ใน Entry 1, 3 และ 5 มนุษย์หักคะแนนหรือให้คะแนนเพียงครึ่งเดียวแม้ว่าเลขมาตราจะถูกต้อง เพราะ "การแสดงผลรวมย่อหน้า/ไม่แยกวรรค" ซึ่ง AI ปัจจุบันไม่ได้ตรวจจับเรื่องนี้เลย (AI ดูแค่เลขมาตราตรงหรือไม่)
2.  **AI ไม่ตรวจสอบความครบถ้วนของเนื้อหาตัวบท (Incomplete Text):** ใน Entry 2 มนุษย์ระบุว่า "ใส่ข้อความมาไม่ครบ" (เช่น ขาดวรรค 2) แต่ AI ให้คะแนนเท่ากันโดยไม่ได้ตัดคะแนนในจุดนี้ชัดเจน
3.  **AI อะลุ่มอล่วยกับมาตราที่ไม่เกี่ยวข้องมากเกินไป (Leninecy on Irrelevant Citations):** ใน Entry 4 AI ให้คะแนน 0.5 เพราะมีมาตราถูกปนอยู่บ้าง แต่มนุษย์ให้ 0 เพราะมีการยกมาตราที่ไม่เกี่ยวข้องเลยมาปน ทำให้คำตอบสับสน (Hallucination/Irrelevant) ซึ่ง Prompt เดิมระบุว่า "ไม่ถือว่าผิด" หากไม่ออกนอกประเด็น แต่ AI ตีความคำว่า "เกี่ยวข้อง" กว้างเกินไป

---

## 2. ข้อเสนอแก้ไขเฉพาะจุด (Specific Fixes)

### จุดที่ 1: เพิ่มเกณฑ์ตรวจสอบรูปแบบและความครบถ้วนของตัวบท
**ส่วนที่ต้องแก้:** `เกณฑ์การประเมิน` (เดิมเน้นแค่เลขมาตรา)
**ข้อความใหม่ที่เสนอ:**
```markdown
# เกณฑ์การประเมิน
1. **ความถูกต้องของมาตรา:** ตรวจสอบว่าเลขมาตราและชื่อกฎหมายตรงกับเฉลย (EXPECTED)
2. **ความครบถ้วนของเนื้อหา:** ตรวจสอบว่าข้อความในตัวบทกฎหมายที่ยกมา "ครบถ้วนทุกวรรค" ตามที่กฎหมายกำหนด ไม่มีการตัดทอนสาระสำคัญ
3. **รูปแบบการแสดงผล (Formatting):** ตรวจสอบการจัดย่อหน้าของตัวบทกฎหมาย
   - ต้องมีการ "ขึ้นย่อหน้าใหม่" เมื่อเป็นคนละวรรค หรือคนละอนุมาตรา
   - ห้ามนำข้อความหลายวรรคมารวมเป็นย่อหน้าเดียวกัน (Merged Paragraphs) หากพบให้ถือเป็นข้อบกพร่อง
4. **ความเกี่ยวข้อง:** ตรวจสอบมาตราที่อ้างอิงเพิ่มเติม
   - หากมีการอ้างอิงมาตราที่ "ไม่เกี่ยวข้อง" หรือ "เกินความจำเป็น" จนทำให้การปรับบทกฎหมายสับสน ให้ถือเป็นข้อบกพร่อง
```
**เหตุผล:** เพื่อแก้ปัญหาใน Entry 1, 3, 5 ที่มนุษย์หักคะแนนเรื่องการรวมย่อหน้า และ Entry 2 เรื่องเนื้อหาขาดหาย

### จุดที่ 2: ปรับนิยามผลการประเมิน (Rubric) ให้สะท้อน Human Score
**ส่วนที่ต้องแก้:** `ผลการประเมิน` (เดิมกว้างเกินไป)
**ข้อความใหม่ที่เสนอ:**
```markdown
# ผลการประเมิน (Score Rubric)
- **1.0 (ถูกต้องสมบูรณ์):** อ้างอิงเลขมาตราหลักครบถ้วนตามเฉลย เนื้อหาตัวบทครบทุกวรรค และ **มีการเว้นวรรค/ย่อหน้าถูกต้องตามรูปแบบกฎหมาย**
- **0.5 (ถูกต้องบางส่วน หรือ มีข้อบกพร่อง):**
  - อ้างอิงมาตราหลักถูกต้องแต่ไม่ครบถ้วน
  - หรือ อ้างอิงครบถ้วนแต่ **รูปแบบผิด** (เช่น รวมย่อหน้า, เนื้อหามาตราขาดหาย)
  - หรือ มีการอ้างอิงมาตราที่ไม่เกี่ยวข้องปะปนมา
- **0 (ไม่ถูกต้อง):** อ้างอิงมาตราผิด, ไม่ตรงประเด็น, ขาดมาตราหลักที่สำคัญที่สุด (Key Section), หรืออ้างอิงมาตรามั่วซั่วจนจับใจความไม่ได้
```
**เหตุผล:** เพื่อให้ AI สามารถให้คะแนน 0.5 ในกรณีที่ "มาตราถูกแต่ Format ผิด" (Entry 5) และให้คะแนน 0 ในกรณีที่มีมาตราขยะปนมาเยอะเกินไป (Entry 4)

---

## 3. เกณฑ์ที่ควรเพิ่ม/ปรับ (Additional Criteria)

ควรเพิ่มส่วน **"Chain of Thought for Scoring"** เพื่อบังคับให้ AI คิดทีละขั้นตอนก่อนให้คะแนน จะช่วยเรื่องความแม่นยำ:

```markdown
# ขั้นตอนการพิจารณา (Reasoning Steps)
1. ระบุ "มาตราหลัก" (Key Sections) ใน EXPECTED ว่ามีอะไรบ้าง
2. ตรวจสอบ OUTPUT ว่ามี "มาตราหลัก" ครบหรือไม่?
3. ตรวจสอบ OUTPUT ว่ามี "มาตราขยะ" (Irrelevant Sections) ที่ทำให้สับสนหรือไม่?
4. **ตรวจสอบเชิงลึก (Format Check):** อ่านข้อความตัวบทใน OUTPUT ว่ามีการนำ "วรรค 1 และ วรรค 2" มารวมบรรทัดเดียวกันหรือไม่? ถ้ามี ต้องหักคะแนน
5. สรุปคะแนนตามเกณฑ์
```

---

## 4. ผลกระทบที่คาดหวัง (Expected Impact)

1.  **คะแนนตรงกับ Entry 5 และ 1, 3 มากขึ้น:** จากเดิม AI ให้เต็ม (1) หรือเกือบเต็ม ในข้อที่ Format ผิด AI จะปรับลดเหลือ 0.5 ตามมาตรฐานมนุษย์ทันที เพราะมีคำสั่งเรื่อง "Merged Paragraphs" ชัดเจน
2.  **คะแนนตรงกับ Entry 4 มากขึ้น:** AI จะกล้าให้คะแนน 0 หากพบมาตราที่ไม่เกี่ยวข้อง (Irrelevant) ปะปนมา เพราะเกณฑ์ใหม่ระบุให้มองเป็นข้อบกพร่องชัดเจน
3.  **ความน่าเชื่อถือสูงขึ้น:** ระบบจะดู "ละเอียด" เหมือนผู้เชี่ยวชาญกฎหมายที่ให้ความสำคัญกับถ้อยคำและรูปแบบ ไม่ใช่แค่ดูเลขมาตรา

In [12]:
judgement_suggestions = reviewer.suggest_prompt_edits(reviews, "judgement")
print(judgement_suggestions)

จากการวิเคราะห์ข้อมูลความแตกต่างระหว่างคะแนนของ AI (Auto Score) และมนุษย์ (Human Score) พบว่ามีช่องว่างสำคัญในด้านการตีความบริบทความเสี่ยงทางธุรกิจ (ธนาคาร), ความลึกของการตรวจสอบตรรกะกฎหมาย (Legal Logic), และประเด็นเรื่องรูปแบบการนำเสนอ (UX/Formatting) ซึ่ง Prompt ปัจจุบันยังไม่ครอบคลุม

นี่คือข้อเสนอแนะในการปรับปรุง Prompt ครับ

---

## 1. สรุปปัญหาที่พบ

1.  **ขาดมิติเรื่องรูปแบบและการนำเสนอ (Formatting & UX):** มนุษย์ให้ความสำคัญกับการจัดย่อหน้าของตัวบทกฎหมาย (การแยกวรรค) มาก (พบใน Entry 1, 3, 5) แต่ Prompt ปัจจุบันไม่ได้สั่งให้ AI ตรวจสอบเรื่องนี้ ทำให้ AI ให้คะแนนเต็มในขณะที่มนุษย์หักคะแนน
2.  **การตรวจสอบตรรกะกฎหมายยังไม่ลึกพอ (Superficial Logic Check):** ใน Entry 4 AI ให้คะแนนเต็มเพราะมีการอ้างมาตราถูกต้องและระบุผลลัพธ์ (โมฆียะ) ถูกต้องตามคีย์เวิร์ด แต่พลาดประเด็นสำคัญคือ "การปรับบทกฎหมายกับข้อเท็จจริง" (Application of Law) โดยเฉพาะเรื่องข้อยกเว้น ทำให้ผลสรุปผิดเพี้ยนไปจากความจริง
3.  **ความเข้มงวดเรื่องผลลัพธ์ vs ความเสี่ยงทางธุรกิจ:** ใน Entry 1 AI ตัดสินว่าผิดทันทีเพราะผลลัพธ์ไม่ตรงเป๊ะ แต่ในมุมมองธนาคาร (มนุษย์) อาจมองเรื่องการบริหารความเสี่ยง (Risk Management) ว่าคำตอบนั้น "ยอมรับได้" หรือ "มีความเสี่ยง" ในระดับที่ต่างกัน Prompt ปัจจุบันมองเพียง ถูก/ผิด ตามเฉลยเป๊ะๆ

---

## 2. ข้อเสนอแก้ไขเฉพาะจุด

### จุดที่ 1: เพิ่มบริบทผู้เชี่ยวชาญให้ชัดเจนขึ้น
**ส่วนที่ต้องแก้:** `คุณคือผู้เชี่ยวชาญทางกฎหมายที่ทำหน้าที่ประเมินคุณภาพคำตอบ...`
**ข้อความใหม่ที่เสนอ:**
```text
คุณคือผู้เชี่ยวชาญทางกฎหมายและระเบียบปฏิบัติของธนาคาร ที่ทำหน้าที่ประเมินคุณภาพคำตอบเพื่อให้คะแนน
คุณต้องคำนึงถึงความถูกต้องตามหลักกฎหมาย, การบริหารความเสี่ยงของธนาคาร, และความชัดเจนในการสื่อสาร (Formatting)
```
**เหตุผล:** เพื่อให้ AI ไม่ได้มองแค่ตัวหนังสือในประมวลกฎหมาย แต่ตระหนักถึงบริบทการนำไปใช้จริงในธุรกิจธนาคาร ซึ่งจะช่วยลดช่องว่างใน Entry 1

### จุดที่ 2: เพิ่มเกณฑ์ตรวจสอบรูปแบบ (Formatting)
**ส่วนที่ต้องแก้:** ส่วน `เกณฑ์การประเมิน`
**ข้อความใหม่ที่เสนอ:** (เพิ่มต่อท้ายเกณฑ์เดิม)
```text
- ตรวจสอบรูปแบบการนำเสนอ (Formatting): หากมีการอ้างอิงตัวบทกฎหมายที่มีหลายวรรค คำตอบต้องมีการ "แยกย่อหน้า" หรือเว้นบรรทัดให้ชัดเจน ไม่นำมารวมเป็นก้อนเดียวกัน เพื่อให้อ่านง่ายและถูกต้องตามรูปแบบเอกสารกฎหมาย
```
**เหตุผล:** แก้ปัญหาใน Entry 1, 3, 5 ที่มนุษย์หักคะแนนเรื่องการแสดงผล (UX) ที่นำวรรคกฎหมายมารวมกัน

### จุดที่ 3: ปรับปรุงการตรวจสอบการใช้กฎหมาย (Application of Law)
**ส่วนที่ต้องแก้:** `ตรวจสอบว่าคำวินิจฉัยอ้างอิงมาตรากฎหมายที่ถูกต้องตามข้อ 1 ของเฉลยหรือไม่`
**ข้อความใหม่ที่เสนอ:**
```text
- ตรวจสอบ "การปรับบทกฎหมายกับข้อเท็จจริง" (Application of Law): ไม่เพียงแค่ดูว่าเลขมาตราตรงกัน แต่ต้องตรวจสอบว่าเหตุผลที่ใช้ในการวินิจฉัย (Reasoning) สอดคล้องกับข้อยกเว้นหรือเงื่อนไขในเฉลยหรือไม่ (เช่น การอ้างข้อยกเว้นต้องสมเหตุสมผลกับสถานการณ์ในโจทย์)
```
**เหตุผล:** แก้ปัญหาใน Entry 4 ที่ AI ตรวจแค่ว่ามีเลขมาตรา 24 และคำว่า "โมฆียะ" ก็ให้ถูกแล้ว ทั้งที่การให้เหตุผลเรื่องข้อยกเว้นนั้นผิด

---

## 3. เกณฑ์ที่ควรเพิ่ม/ปรับ (ในส่วนเกณฑ์การประเมิน)

ควรปรับเปลี่ยนเกณฑ์การประเมินให้ละเอียดขึ้น โดยเฉพาะเกณฑ์การให้คะแนน (Scoring Rubric) เพื่อให้ AI ตัดสินใจได้ซับซ้อนกว่าแค่ ถูก/ผิด

**ข้อความใหม่ที่เสนอในส่วน "ผลการประเมิน":**

```text
# แนวทางการตัดสินผลการประเมิน (Decision Logic)
1. **ตอบได้ถูกต้อง ชัดเจน ครอบคลุม:**
   - วินิจฉัยผลทางกฎหมายถูกต้อง (Conclusion matches)
   - อ้างอิงเหตุผลและมาตราสำคัญครบถ้วน (Reasoning matches)
   - การจัดรูปแบบ (Formatting) ถูกต้อง แยกวรรคตอนชัดเจน

2. **ตอบได้ถูกต้อง แต่ไม่ครอบคลุม หรือมีข้อบกพร่องเล็กน้อย:**
   - วินิจฉัยผลทางกฎหมายถูกต้อง แต่เหตุผลประกอบบางส่วนหายไป
   - หรือ เนื้อหาถูกต้องครบถ้วน แต่การจัดรูปแบบ (Formatting) ไม่ดี (เช่น รวมวรรคกฎหมาย)
   - หรือ อ้างอิงมาตราผิด/เกิน แต่ผลวินิจฉัยและความเสี่ยงยังอยู่ในเกณฑ์ที่ยอมรับได้

3. **ไม่ถูกต้องตามเฉลย:**
   - วินิจฉัยผลทางกฎหมายผิด (Wrong Conclusion)
   - หรือ ปรับบทกฎหมายผิดพลาดอย่างร้ายแรง (เช่น อ้างข้อยกเว้นผิดกรณีใน Entry 4)
   - หรือ ให้คำแนะนำที่สร้างความเสี่ยงต่อธนาคาร
```

---

## 4. ผลกระทบที่คาดหวัง

1.  **คะแนนเรื่อง Formatting ตรงกับมนุษย์:** AI จะเริ่มหักคะแนนหรือไม่ให้คะแนนเต็มในกรณีที่คำตอบถูกต้องแต่เขียนตัวบทกฎหมายติดกันเป็นพืด (Entry 3, 5)
2.  **ลด False Positive ในเคสซับซ้อน:** ในกรณีแบบ Entry 4 ที่ AI เคยให้เต็มเพราะเห็นคีย์เวิร์ดครบ AI จะเปลี่ยนมาให้คะแนนตก (0) เพราะถูกสั่งให้ตรวจสอบ Logic ของการใช้ข้อยกเว้น (Application of Law) แทนการตรวจแค่ Reference matching
3.  **ความยืดหยุ่นในบริบทธนาคาร:** การเพิ่มบริบทเรื่อง "ความเสี่ยงธนาคาร" จะช่วยให้ AI เข้าใจว่าทำไมมนุษย์ถึงให้คะแนน 0.5 ในเคสที่อ้างอิงกฎหมายไม่ครบแต่แนวทางปฏิบัติปลอดภัย หรือให้ 0 ในเคสที่แนวทางปฏิบัติเสี่ยง (Entry 1)

## 5. (Option) ตัวอย่าง Prompt ฉบับสมบูรณ์

```markdown
คุณคือผู้เชี่ยวชาญทางกฎหมายและระเบียบปฏิบัติของธนาคาร ที่ทำหน้าที่ประเมินคุณภาพคำตอบ

# งานของคุณ
ให้คะแนนความถูกต้องของ **ข้อ 2 (คำวินิจฉัย)** ในคำตอบ (OUTPUT) โดยเทียบกับเฉลย (EXPECTED) อย่างละเอียด

# รูปแบบข้อมูลเฉลย
เฉลย (EXPECTED) อยู่ในรูปแบบ Markdown ที่แบ่งเป็นหัวข้อ:
- `## 1. มาตรากฎหมายที่เกี่ยวข้อง`
- `## 2. คำวินิจฉัย` (ใช้เป็นเกณฑ์หลัก)
- `## 3. ข้อสรุปและข้อเสนอแนะ`

# เกณฑ์การประเมิน (Criteria)
1. **ความถูกต้องของผลลัพธ์ (Result & Risk):** ผลทางกฎหมาย (สมบูรณ์/โมฆะ) ตรงกับเฉลยหรือไม่ และคำแนะนำนั้นปลอดภัยสำหรับการปฏิบัติงานของธนาคารหรือไม่
2. **ตรรกะและการปรับบท (Logic & Application):** การยกข้อกฎหมายหรือข้อยกเว้นมาใช้นั้น สมเหตุสมผลกับข้อเท็จจริงในโจทย์หรือไม่ (ไม่ใช่ดูแค่ว่าเลขมาตราตรงกัน แต่ดูว่าเหตุผลที่ใช้นั้นถูกต้องตามเฉลย)
3. **ความครบถ้วน (Coverage):** ครอบคลุมทุกประเด็นหรือทุกสถานการณ์ตามเฉลยหรือไม่
4. **รูปแบบการนำเสนอ (Formatting/UX):** การอ้างอิงตัวบทกฎหมาย **ต้องแยกวรรค/แยกย่อหน้า** ให้ถูกต้องตามต้นฉบับ หากนำหลายวรรคมารวมเป็นย่อหน้าเดียวถือเป็นข้อบกพร่อง

# ผลการประเมิน (Scoring)
เลือก 1 ข้อที่ตรงที่สุด:
- **ตอบได้ถูกต้อง ชัดเจน ครอบคลุม**: เนื้อหาถูกต้อง เหตุผลถูกต้อง และจัดรูปแบบ (Formatting) ได้ดีเยี่ยม แยกวรรคตอนชัดเจน
- **ไม่ถูกต้องตามเฉลย**: วินิจฉัยผลผิด, ปรับบทกฎหมายผิดข้อเท็จจริง (เช่น อ้างข้อยกเว้นผิด), หรือให้คำแนะนำที่เสี่ยงต่อธนาคาร
- **ตอบได้ถูกต้อง แต่ไม่ครอบคลุม หรือมีข้อบกพร่อง**: วินิจฉัยถูกแต่เหตุผลไม่ครบ, หรือเนื้อหาถูกแต่จัดรูปแบบไม่ดี (เช่น รวมวรรคกฎหมาย), หรืออ้างอิงมาตราไม่ครบแต่สาระสำคัญยังถูกต้อง

# ข้อมูล
EXPECTED: {{expected}}
OUTPUT: {{output}}
```

In [13]:
suggestion_suggestions = reviewer.suggest_prompt_edits(reviews, "suggestion")
print(suggestion_suggestions)

จากการวิเคราะห์ Prompt ปัจจุบันเทียบกับข้อมูลความขัดแย้ง (Discrepancy) ระหว่าง AI และมนุษย์ พบประเด็นสำคัญที่ทำให้คะแนนไม่ตรงกัน และขอเสนอแนวทางปรับปรุงดังนี้ครับ

---

## 1. สรุปปัญหาที่พบ

1.  **AI ตัดสินด้วย "ทฤษฎีกฎหมาย" แต่มนุษย์ตัดสินด้วย "นโยบายธนาคาร/ความเสี่ยง":**
    *   ใน Entry 1 AI ให้คะแนนเต็มเพราะคำตอบถูกต้องตามประมวลกฎหมายแพ่ง (ป.พ.พ.) แต่ Human ให้ 0 เพราะในทางปฏิบัติธนาคารต้องการ "ปิดความเสี่ยง" จึงต้องให้ตั้งผู้จัดการมรดกเท่านั้น AI ไม่เข้าใจบริบทว่า "ระเบียบปฏิบัติ (Policy)" สำคัญกว่า "สิทธิตามกฎหมายทั่วไป" ในบริบทนี้
2.  **AI พยายาม "เถียง" เฉลย (EXPECTED):**
    *   ใน Entry 1 AI ระบุว่า OUTPUT ดีกว่า EXPECTED เพราะอ้างกฎหมายใหม่กว่า แต่ระบบ Scorer ที่ดีต้องยึด EXPECTED เป็น "ความถูกต้องสัมบูรณ์" (Ground Truth) ในบริบทของการตรวจข้อสอบหรือตรวจสอบความถูกต้องตามระเบียบองค์กร ไม่ใช่เวทีถกเถียงทางวิชาการ
3.  **ขาดมิติเรื่อง "ความสามารถในการนำไปใช้ปฏิบัติจริง" (Actionability):**
    *   ใน Entry 3 Human ต้องการคำแนะนำที่เจ้าหน้าที่หน้างานนำไปบอกลูกค้าต่อได้เลย (เช่น แนะนำไปอัยการ) แต่ AI มองแค่ว่าตอบถูกกฎหมายก็พอแล้ว
4.  **ขาดการตรวจสอบเรื่องรูปแบบ (Formatting) และความกระชับ:**
    *   ใน Entry 4 และ 5 Human หักคะแนนเรื่องการจัดย่อหน้า และการใส่ข้อมูลส่วนเกิน (Information overload) ซึ่ง Prompt ปัจจุบันไม่ได้ระบุให้ตรวจสอบเรื่อง UX/UI หรือความเยิ่นเย้อ

---

## 2. ข้อเสนอแก้ไขเฉพาะจุด

### 2.1 ปรับบทบาทและเป้าหมาย (Role & Objective)
เปลี่ยนจากการให้ AI เป็น "ผู้เชี่ยวชาญกฎหมาย" (ที่มักจะตีความกว้าง) เป็น "ผู้ตรวจสอบการปฏิบัติตามนโยบาย"

*   **ส่วนที่ต้องแก้:**
    ```markdown
    คุณคือผู้เชี่ยวชาญทางกฎหมายที่ทำหน้าที่ประเมินคุณภาพคำตอบ...
    ```
*   **ข้อความใหม่ที่เสนอ:**
    ```markdown
    คุณคือ "ผู้ตรวจสอบการปฏิบัติตามนโยบายและกฎหมายของธนาคาร" (Bank Compliance Auditor)
    หน้าที่ของคุณคือประเมินว่าคำตอบ (OUTPUT) สอดคล้องกับแนวทางปฏิบัติที่ระบุในเฉลย (EXPECTED) อย่างเคร่งครัดหรือไม่ โดยเน้นการ "ปิดความเสี่ยง" และ "การนำไปปฏิบัติได้จริงของเจ้าหน้าที่สาขา" เป็นสำคัญ
    ```
*   **เหตุผล:** บังคับให้ AI มองผ่านเลนส์ของคนทำงานธนาคารที่ต้องระวังความเสี่ยง (Risk Averse) มากกว่านักกฎหมายที่มองเรื่องสิทธิ (Rights Based) ซึ่งจะแก้ปัญหาใน Entry 1 และ 2

### 2.2 เพิ่มกฎเหล็กเรื่องการยึดเฉลย (Strict Adherence to Expected)
ป้องกัน AI ให้คะแนนคำตอบที่ "ถูกกฎหมายแต่ผิดระเบียบธนาคาร"

*   **ส่วนที่ต้องแก้:**
    ```markdown
    ให้คะแนนความถูกต้องของ **ข้อ 3 (ข้อสรุปและข้อเสนอแนะ)** ในคำตอบ (OUTPUT) โดยเทียบกับเฉลย (EXPECTED)
    ```
*   **ข้อความใหม่ที่เสนอ:**
    ```markdown
    ให้ประเมินความถูกต้องของ **ข้อ 3 (ข้อสรุปและข้อเสนอแนะ)** โดยยึดเนื้อหาในเฉลย (EXPECTED) เป็นเกณฑ์ตัดสินสูงสุด (Absolute Truth)
    - หาก OUTPUT ขัดแย้งกับ EXPECTED ในแง่ของนโยบายหรือขั้นตอนปฏิบัติ (แม้จะถูกต้องตามทฤษฎีกฎหมายทั่วไป) ให้ถือว่า "ไม่ถูกต้อง" ทันที
    - ห้ามใช้ความรู้ภายนอกมาโต้แย้งว่า EXPECTED ผิด หรือ ล้าสมัย
    ```
*   **เหตุผล:** แก้ปัญหา Entry 1 ที่ AI ให้คะแนนเต็มโดยอ้างว่าคำตอบดีกว่าเฉลย

### 2.3 ปรับเกณฑ์การประเมิน (Evaluation Criteria)
เพิ่มเรื่องความกระชับและการแนะนำลูกค้า

*   **ส่วนที่ต้องแก้:**
    ```markdown
    - ตรวจสอบว่าข้อสรุปสอดคล้องกับคำวินิจฉัยและเฉลยหรือไม่
    - ตรวจสอบว่าข้อเสนอแนะมีความเป็นรูปธรรมและนำไปปฏิบัติได้จริงหรือไม่
    - ตรวจสอบว่าครอบคลุมข้อควรระวังและความเสี่ยงทางกฎหมายที่สำคัญหรือไม่
    ```
*   **ข้อความใหม่ที่เสนอ:**
    ```markdown
    1. **ความถูกต้องตามธงคำตอบ:** ข้อสรุปต้องตรงกับ EXPECTED โดยเฉพาะประเด็น "ทำได้/ทำไม่ได้" (Yes/No) หากธงคำตอบบอกว่าไม่ได้ แต่คำตอบบอกว่าได้ (แม้มีข้อยกเว้นทางกฎหมาย) ให้ถือว่าผิด
    2. **คำแนะนำเชิงปฏิบัติ (Actionable Advice):** ข้อเสนอแนะต้องช่วยให้เจ้าหน้าที่ธนาคารทำงานง่ายขึ้น หรือแนะนำช่องทางช่วยเหลือลูกค้าได้ชัดเจน (เช่น การแนะนำหน่วยงานภายนอกที่เกี่ยวข้องตามเฉลย)
    3. **ความกระชับและรูปแบบ:** คำตอบต้องไม่มีข้อมูลส่วนเกินที่ไม่จำเป็น (No Fluff) และมีการจัดรูปแบบที่อ่านง่าย ไม่รวมย่อหน้าจนสับสน
    ```
*   **เหตุผล:** ครอบคลุม Entry 3 (แนะนำหน่วยงาน), Entry 4 (ข้อมูลเกิน), และ Entry 5 (จัดรูปแบบ)

---

## 3. เกณฑ์ที่ควรเพิ่ม/ปรับ (ในส่วนผลการประเมิน)

ปรับคำอธิบายของตัวเลือกคะแนนให้ชัดเจนขึ้น เพื่อดักจับกรณี "ถูกกฎหมายแต่ผิดนโยบาย"

**จากเดิม:**
> - ตอบได้ถูกต้อง ชัดเจน ครอบคลุม ให้ข้อเสนอแนะที่เป็นไปได้จริง
> - ไม่ถูกต้องตามเฉลย
> - ตอบได้ถูกต้อง แต่ไม่ครอบคลุม มีเนื้อหาสำคัญตกหล่น

**ปรับปรุงเป็น:**
> - **ถูกต้องและสมบูรณ์:** สรุปผลทางกฎหมายและนโยบายตรงกับเฉลยครบถ้วน ให้คำแนะนำที่เป็นประโยชน์ต่อเจ้าหน้าที่หน้างาน รูปแบบอ่านง่าย ไม่มีข้อมูลส่วนเกิน
> - **ถูกต้องแต่มีข้อบกพร่อง:** สรุปผลถูกต้องตามเฉลย แต่ขาดคำแนะนำที่สำคัญ (เช่น หน่วยงานที่ลูกค้าควรไปติดต่อ) หรือมีข้อมูลส่วนเกินที่ไม่จำเป็น หรือการจัดรูปแบบอ่านยาก
> - **ไม่ถูกต้อง/มีความเสี่ยง:** สรุปผลขัดแย้งกับเฉลย (เช่น เฉลยห้ามแต่คำตอบบอกให้ทำได้) หรือให้คำแนะนำที่อาจก่อให้เกิดความเสี่ยงต่อธนาคาร แม้จะอ้างอิงกฎหมายถูกต้องก็ตาม

---

## 4. ผลกระทบที่คาดหวัง

1.  **ลดความขัดแย้งเรื่องนโยบาย (Policy Alignment):** คะแนนจะตรงกับมนุษย์มากขึ้นในเคสที่กฎหมายเปิดช่องแต่ธนาคารปิดช่อง (เช่น เรื่องมรดก) เพราะ Prompt บังคับให้ยึด EXPECTED เป็นหลัก
2.  **เพิ่มความใส่ใจรายละเอียด (Detail Oriented):** AI จะเริ่มหักคะแนนเรื่อง Formatting และข้อมูลส่วนเกิน (User Experience) ซึ่งเป็นสิ่งที่ผู้ตรวจสอบมนุษย์ให้ความสำคัญ
3.  **คำแนะนำที่จับต้องได้ (Practicality):** AI จะมองหา "How-to" ในคำตอบมากขึ้น ไม่ใช่แค่ "Legal Theory" ทำให้สอดคล้องกับความต้องการทางธุรกิจ

## 7. Full Pipeline (Alternative)
Run everything in one call using `run_full_review`.

In [ ]:
# report = reviewer.run_full_review(data)
#
# print("=== Overall Score Analysis ===")
# print(report.overall_score_analysis)
#
# for scorer_name, suggestion in report.prompt_suggestions.items():
#     print(f"\n=== Prompt Suggestions: {scorer_name} ===")
#     print(suggestion)