# Eval Feedback Review
Compare human reviewer scores/feedback against automated eval scorers, identify discrepancies, and suggest prompt improvements.

## Setup

In [1]:
from legal_rag.eval_review import EvalReviewClient, ScorerResult
from config import *

import json 
import copy
import math
import os
import time
import pandas as pd

In [2]:
from google import genai
from google.genai import types

client = genai.Client(api_key=os.getenv("GENAI_API_KEY"))

In [3]:
EVAL_RESULTS_FOLDER = os.path.join(EVAL_RESULTS_ROOT_PATH, f"eval_scorer_{EVAL_AI_PROMPT_VERSION}")
EVAL_RESULTS_FOLDER

'docs/KKP/LNC/eval_results/eval_scorer_v02'

## 1. Initialize Review Client

In [73]:
REVIEW_AI_PROMPT_VERSION = "v07"
NEW_EVAL_AI_PROMPT_VERSION = "v08"


reviewer = EvalReviewClient(
    eval_model=EVAL_AI_MODEL,
    review_model=REVIEW_AI_MODEL,
    eval_prompt_version=REVIEW_AI_PROMPT_VERSION,
    prompt_version=REVIEW_AI_PROMPT_VERSION,
)
reviewer

## 2. Load & Transform Eval Results JSON

In [74]:
data = EvalReviewClient.load_eval_folder(EVAL_RESULTS_FOLDER)

print(f"\nLoaded {len(data)} total entries\n")
for i, d in enumerate(data):
    print(f"Entry {i+1} [{d['source_file']}]: {d['input'][:80]}...")
    print(f"  Auto:  {d['auto_scores']}")
    print(f"  Human: {d['human_scores']}")
    print("-------------------------------")

  Loaded 5 entries from Deposit-Gemini-3.0 Flash Legal V02
  Loaded 5 entries from Deposit-Gemini-3.0 Pro Legal V02
  Loaded 15 entries from HP-Gemini-3.0 Flash Legal v02
  Loaded 20 entries from Lending-Gemini-3.0 Flash Legal V02

Total: 45 entries from 4 files

Loaded 45 total entries

Entry 1 [Deposit-Gemini-3.0 Flash Legal V02]: เจ้าของบัญชีเงินฝากถึงแก่กรรม บุคคลที่อ้างว่าเป็นทายาทขอดำเนินการจัดการบัญชี เช่...
  Auto:  {'reference': 0, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0}
-------------------------------
Entry 2 [Deposit-Gemini-3.0 Flash Legal V02]: นิติบุคคลเปิดบัญชีเงินฝาก ใช้หนังสือแสดงความประสงค์เปิดบัญชีแล้วลงนามโดยกรรมการผ...
  Auto:  {'reference': 0.5, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0.5}
-------------------------------
Entry 3 [Deposit-Gemini-3.0 Flash Legal V02]: เจ้าของบัญชีเงินฝากที่เสียชีวิตเป็นคนต่างชาติ ผู้ที่อ้างว่าเป็นทายาทมาขอถอนเงิน ...
  Auto:  {'reference': 0.5, 'judgement': 0.5, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 1, 'suggestion': 0.5}
-------------------------------
Entry 4 [Deposit-Gemini-3.0 Flash Legal V02]: ผู้เยาว์สามารถเปิดบัญชีเงินฝากกับธนาคารได้หรือไม่...
  Auto:  {'reference': 0.5, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 1}
-------------------------------
Entry 5 [Deposit-Gemini-3.0 Flash Legal V02]: กรณีลูกค้าขอเบิกถอนเงินฝากประจำ ธนาคารไม่ยินยอมให้ถอนก่อนครบกำหนดระยะเวลาฝากของล...
  Auto:  {'reference': 1, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 6 [Deposit-Gemini-3.0 Pro Legal V02]: เจ้าของบัญชีเงินฝากถึงแก่กรรม บุคคลที่อ้างว่าเป็นทายาทขอดำเนินการจัดการบัญชี เช่...
  Auto:  {'reference': 0.5, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0.5, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 7 [Deposit-Gemini-3.0 Pro Legal V02]: นิติบุคคลเปิดบัญชีเงินฝาก ใช้หนังสือแสดงความประสงค์เปิดบัญชีแล้วลงนามโดยกรรมการผ...
  Auto:  {'reference': 0.5, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0.5, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 8 [Deposit-Gemini-3.0 Pro Legal V02]: เจ้าของบัญชีเงินฝากที่เสียชีวิตเป็นคนต่างชาติ ผู้ที่อ้างว่าเป็นทายาทมาขอถอนเงิน ...
  Auto:  {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0.5}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0.5}
-------------------------------
Entry 9 [Deposit-Gemini-3.0 Pro Legal V02]: ผู้เยาว์สามารถเปิดบัญชีเงินฝากกับธนาคารได้หรือไม่...
  Auto:  {'reference': 0.5, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0.5}
-------------------------------
Entry 10 [Deposit-Gemini-3.0 Pro Legal V02]: กรณีลูกค้าขอเบิกถอนเงินฝากประจำ ธนาคารไม่ยินยอมให้ถอนก่อนครบกำหนดระยะเวลาฝากของล...
  Auto:  {'reference': 1, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 11 [HP-Gemini-3.0 Flash Legal v02]: ประกาศ สคบ. 65 มีผลใช้บังคับนับวันที่ใด...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 1, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 12 [HP-Gemini-3.0 Flash Legal v02]: ในกรณีที่ผู้ให้เช่าซื้อได้นำรถยนต์ออกขายโดยวิธีประมูลตามประกาศ สคบ. 65 เรียบร้อย...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 1, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 13 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ. ปี 65 กำหนดเกี่ยวกับการเข้าสู้ราคาของผู้ให้เช่าซื้อในการประมูลหรื...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 1, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 14 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ. ปี 65 ในกรณีที่จะกำหนดให้การผิดสัญญาเช่าซื้อที่ผู้ให้เช่าซื้อมีสิ...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 1, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 15 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ. ปี 65 ผู้ให้เช่าซื้อสามารถคิดค่าใช้จ่ายในกรณีที่ผู้เช่าซื้อมีการร...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 1, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 16 [HP-Gemini-3.0 Flash Legal v02]: ค่าใช้จ่ายที่ผู้ให้เช่าซื้อเรียกเก็บได้ ตามประกาศ สคบ ปี 65 คือค่าอะไรบ้าง...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 1, 'judgement': 1, 'suggestion': 0}
-------------------------------
Entry 17 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ. ปี 65 ในกรณีที่ผู้ให้เช่าซื้อนำรถยนต์ออกขายโดยวิธีประมูลตามขั้นตอ...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 18 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ. ปี 65 ผู้ให้เช่าซื้อสามารถกำหนดให้ผู้เช่าซื้อเปลี่ยนแปลงผู้ค้ำประ...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 0, 'judgement': 1, 'suggestion': 0}
-------------------------------
Entry 19 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ 61 ผู้ให้เช่าซื้อสามารถคิดเบี้ยปรับในกรณีที่ผู้เช่าซื้อผิดนัดชำระค...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 0, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 20 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ 65 ในกรณีที่มีผู้ค้ำประกัน ผู้ให้เช่าซื้อต้องจัดทำสัญญาค้ำประกันอย...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 0, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 21 [HP-Gemini-3.0 Flash Legal v02]: ในกรณีที่รถยนต์ที่เช่าซื้อถูกทำลายโดยสิ้นเชิง โดยไม่ใช่ความผิดของผู้เช่าซื้อ ผู้...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 0, 'judgement': 1, 'suggestion': 0}
-------------------------------
Entry 22 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ 65 ผู้ให้เช่าซื้อสามารถคิดเบี้ยปรับในกรณีที่ผู้เช่าซื้อผิดนัดชำระค...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 0, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 23 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ 65 มูลหนี้ส่วนที่ขาดอยู่ตามสัญญาเช่าซื้อให้คำนวณจากอะไรบ้าง...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 0, 'judgement': 1, 'suggestion': 1}
-------------------------------
Entry 24 [HP-Gemini-3.0 Flash Legal v02]: ผู้ให้เช่าซื้อมีหน้าที่จะต้องแจ้งผู้เช่าซื้อ และผู้ค้ำประกัน (ถ้ามี)ให้สามารถใช้...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 25 [HP-Gemini-3.0 Flash Legal v02]: ตามประกาศ สคบ 65 หากผู้ให้เช่าซื้อประสงค์จะนำเงินค่างวดของผู้เช่าซื้อ มาหักชำระเ...
  Auto:  {'reference': None, 'judgement': None, 'suggestion': None}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 26 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 15. ผู้ให้หลักประกันนำบัญชีเงินฝากมาจด BSA ต่อมาเสียชีวิต ธนาคารยังมีบุริมสิ...
  Auto:  {'reference': 0, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 1}
-------------------------------
Entry 27 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 1. (1) ผู้กู้/ผู้ให้หลักประกัน ต้องการนำ stock อะไหล่รถเครื่องจักร ซึ่งเป็นส...
  Auto:  {'reference': 0, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 28 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 11. กรณี rollover ตั๋วสัญญาใช้เงิน (PN) ถือว่ายังเป็นภาระหนี้เดิมที่เกิดก่อน...
  Auto:  {'reference': 0.5, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0.5, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 29 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 16. เมื่อไม่มีภาระหนี้แล้ว ผู้ให้กู้ต้องการที่จะยกเลิกวงเงินสินเชื่อ เพื่อที...
  Auto:  {'reference': 0.5, 'judgement': 0.5, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0.5}
-------------------------------
Entry 30 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 12. คณะกรรมการจัดสรรที่ดินซึ่งเป็นผู้รับประโยชน์ทำหนังสือค้ำประกันซึ่งออกโดย...
  Auto:  {'reference': 0.5, 'judgement': 0.5, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 31 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 9. ธนาคารสามารถหักเงินในบัญชี Escrow Account ของผู้กู้มาชำระหนี้ได้หรือไม่นั...
  Auto:  {'reference': 0.5, 'judgement': 0.5, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0.5}
-------------------------------
Entry 32 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 5. การทำข้อตกลงแปลง OD เป็น TL ระหว่างผู้กู้กับธนาคาร หากผู้ค้ำประกันไม่ลงนา...
  Auto:  {'reference': 0.5, 'judgement': 0.5, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0.5}
-------------------------------
Entry 33 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 19. หากผู้กู้นำที่ดินแปลงที่มีการจดทะเบียนสิทธิเก็บกินไว้มาเป็นหลักประกัน จะ...
  Auto:  {'reference': 0.5, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0}
-------------------------------
Entry 34 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 14. ธนาคารต้องส่งมอบเงินฝากซึ่งจด BSA ไว้ ให้แก่เจ้าหนี้ค่าภาษีอากรตามคำสั่ง...
  Auto:  {'reference': 0.5, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 0, 'suggestion': 0.5}
-------------------------------
Entry 35 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 10. ที่ดินที่ได้มาจากการที่บิดายกให้บุตรโดยเสน่หา บิดาซึ่งเป็นผู้ให้ยังสามาร...
  Auto:  {'reference': 0.5, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 1}
-------------------------------
Entry 36 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 2. หากผู้กู้ได้นำส่งใบอนุญาตก่อสร้างให้แก่ธนาคารตามเงื่อนไขการเบิกวงเงินค่าก...
  Auto:  {'reference': 0.5, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 1}
-------------------------------
Entry 37 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 7. ผู้จำนองที่เป็นผู้ถือหุ้นผู้กู้ เข้าทำสัญญาค้ำประกันเพื่อประกันหนี้ผู้กู้...
  Auto:  {'reference': 1, 'judgement': 0, 'suggestion': 0}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0.5}
-------------------------------
Entry 38 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 3. ผู้กู้ขอให้ออกหนังสือค้ำประกัน L/G ฉบับใหม่ หลังจากวันที่ครบกำหนดระยะเวลา...
  Auto:  {'reference': 1, 'judgement': 0.5, 'suggestion': 0.5}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0.5}
-------------------------------
Entry 39 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 6. ความเห็นทางด้านกฎหมายเพิ่มเติมสำหรับการทำธุรกรรมกับลูกค้าที่อยู่ภายใต้แผน...
  Auto:  {'reference': 1, 'judgement': 0.5, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 0.5, 'suggestion': 0.5}
-------------------------------
Entry 40 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 17. 1. การโอนหุ้นระหว่างที่ติดจำนำอยู่ สามารถทำได้หรือไม่ กระทบสิทธิของธนาคา...
  Auto:  {'reference': 1, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0.5}
-------------------------------
Entry 41 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 20. คู่สมรสของผู้ค้ำประกันไม่ได้ลงนามให้ความยินยอมในการทำสัญญาค้ำประกัน จะบั...
  Auto:  {'reference': 1, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 0.5, 'suggestion': 0.5}
-------------------------------
Entry 42 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 18. ตามที่ BU พิจารณาวงเงินสินเชื่อให้ผู้กู้ที่ 1 และผู้กู้ที่ 2 เป็นวงเงินก...
  Auto:  {'reference': 1, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0.5, 'judgement': 1, 'suggestion': 0.5}
-------------------------------
Entry 43 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 13. ผู้กู้ซื้อที่ดินจากผู้จัดการมรดกตามพินัยกรรม และนำที่ดินดังกล่าวมาเป็นหล...
  Auto:  {'reference': 1, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0.5}
-------------------------------
Entry 44 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 8. ผู้กู้ได้รับการสนับสนุนทางการเงินจากธนาคาร ต่อมาประสงค์จะขอเปลี่ยนแปลงเงื...
  Auto:  {'reference': 1, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 0, 'suggestion': 0.5}
-------------------------------
Entry 45 [Lending-Gemini-3.0 Flash Legal V02]: ข้อ 4. การจำนองครอบไปถึงสิ่งปลูกสร้างที่ไม่ได้ระบุ หรือไม่ และการได้กรรมสิทธิ์สิ...
  Auto:  {'reference': 1, 'judgement': 1, 'suggestion': 1}
  Human: {'reference': 0, 'judgement': 1, 'suggestion': 1}
-------------------------------

In [55]:
# Quick score comparison table (skip entries with None auto scores)
rows = []
for i, d in enumerate(data):
    for key in ["reference", "judgement", "suggestion"]:
        auto = d["auto_scores"][key]
        human = d["human_scores"][key]
        if human is None: continue
        rows.append({
            "entry": i + 1,
            "source_file": d["source_file"],
            "scorer": key,
            "auto_score": auto,
            "human_score": human,
            "diff": auto - human if auto is not None and human is not None else None,
        })

score_df = pd.DataFrame(rows)
score_df

,entry,source_file,scorer,auto_score,human_score,diff
0,1,Deposit-Gemini-3.0 Flash Legal V02,reference,0.0,0.5,-0.5
1,1,Deposit-Gemini-3.0 Flash Legal V02,judgement,0.0,0.5,-0.5
2,1,Deposit-Gemini-3.0 Flash Legal V02,suggestion,0.0,0.0,0.0
3,2,Deposit-Gemini-3.0 Flash Legal V02,reference,0.5,0.5,0.0
4,2,Deposit-Gemini-3.0 Flash Legal V02,judgement,0.0,0.5,-0.5
...,...,...,...,...,...,...
130,44,Lending-Gemini-3.0 Flash Legal V02,judgement,1.0,0.0,1.0
131,44,Lending-Gemini-3.0 Flash Legal V02,suggestion,1.0,0.5,0.5
132,45,Lending-Gemini-3.0 Flash Legal V02,reference,1.0,0.0,1.0
133,45,Lending-Gemini-3.0 Flash Legal V02,judgement,1.0,1.0,0.0
134,45,Lending-Gemini-3.0 Flash Legal V02,suggestion,1.0,1.0,0.0

## 3. Scorer Review

Each scorer is reviewed independently through the same pipeline:
1. **Re-run** the scorer on all entries to get fresh scores + rationale
2. **Compare** re-run scores vs human scores
3. **Analyze discrepancies** between human feedback and auto rationale
4. **Suggest prompt improvements** for the next scorer version

In [56]:
SCORER_NAMES = ["reference", "judgement", "suggestion"]
LIMIT = 10
NUM_RERUN_ROWS = math.floor(LIMIT / len(SCORER_NAMES))
NUM_RERUN_TIMES = math.ceil(len(data) / NUM_RERUN_ROWS)


all_reviews = {}  # scorer_name -> list[EntryReview]
all_suggestions = {}  # scorer_name -> str

In [57]:
# new_reviews = []

# for i in reviews:
#     new_scorer_results = []
#     for j in i.scorer_results:
#         new_scorer_results.append(
#             ScorerResult(
#                 scorer_name=j['scorer_name'],
#                 score=j['score'],
#                 choice=j['choice'],
#                 rationale=j['rationale']
#             )
#         )
#     i.scorer_results = new_scorer_results
#     new_reviews.append(i)

# reviews = new_reviews
# reviews

In [58]:
reviews = []
# 3.1.1 Re-run scorer
for i in range(NUM_RERUN_TIMES):
    start_idx = i * NUM_RERUN_ROWS
    end_idx = min((i + 1) * NUM_RERUN_ROWS, len(data))
    print(f"\nRe-running scorers for entries {start_idx + 1} to {end_idx}...")
    reviews.extend(reviewer.rerun_scorers(data[start_idx:end_idx], SCORER_NAMES))

    print("Sleeping for 20 seconds to avoid rate limits...")
    time.sleep(20)  # Sleep to avoid hitting rate limits  
    print("------------------------------------------------")

reviews

Re-running scorers for entries 1 to 3...
  [1/3] reference: 0.0
  [1/3] judgement: 1.0
  [1/3] suggestion: 0.0
  [2/3] reference: 0.5
  [2/3] judgement: 0.0
  [2/3] suggestion: 0.0
  [3/3] reference: 0.5
  [3/3] judgement: 0.5
  [3/3] suggestion: 0.5
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 4 to 6...
  [1/3] reference: 0.5
  [1/3] judgement: 1.0
  [1/3] suggestion: 0.5
  [2/3] reference: 0.5
  [2/3] judgement: 1.0
  [2/3] suggestion: 1.0
  [3/3] reference: 0.0
  [3/3] judgement: 0.0
  [3/3] suggestion: 0.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 7 to 9...
  [1/3] reference: 0.0
  [1/3] judgement: 0.0
  [1/3] suggestion: 0.0
  [2/3] reference: 0.5
  [2/3] judgement: 0.5
  [2/3] suggestion: 0.5
  [3/3] reference: 0.5
  [3/3] judgement: 1.0
  [3/3] suggestion: 1.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 10 to 12...
  [1/3] reference: 1.0
  [1/3] judgement: 1.0
  [1/3] suggestion: 0.5
  [2/3] reference: 1.0
  [2/3] judgement: 0.0
  [2/3] suggestion: 1.0
  [3/3] reference: 1.0
  [3/3] judgement: 1.0
  [3/3] suggestion: 1.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 13 to 15...
  [1/3] reference: 1.0
  [1/3] judgement: 1.0
  [1/3] suggestion: 1.0
  [2/3] reference: 1.0
  [2/3] judgement: 1.0
  [2/3] suggestion: 1.0
  [3/3] reference: 0.5
  [3/3] judgement: 1.0
  [3/3] suggestion: 1.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 16 to 18...
  [1/3] reference: 1.0
  [1/3] judgement: 1.0
  [1/3] suggestion: 1.0
  [2/3] reference: 0.5
  [2/3] judgement: 1.0
  [2/3] suggestion: 1.0
  [3/3] reference: 0.0
  [3/3] judgement: 1.0
  [3/3] suggestion: 1.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 19 to 21...
  [1/3] reference: 0.5
  [1/3] judgement: 1.0
  [1/3] suggestion: 1.0
  [2/3] reference: 1.0
  [2/3] judgement: 1.0
  [2/3] suggestion: 0.5
  [3/3] reference: 0.5
  [3/3] judgement: 1.0
  [3/3] suggestion: 0.5
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 22 to 24...
  [1/3] reference: 1.0
  [1/3] judgement: 1.0
  [1/3] suggestion: 1.0
  [2/3] reference: 1.0
  [2/3] judgement: 1.0
  [2/3] suggestion: 1.0
  [3/3] reference: 0.5
  [3/3] judgement: 1.0
  [3/3] suggestion: 1.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 25 to 27...
  [1/3] reference: 0.5
  [1/3] judgement: 0.5
  [1/3] suggestion: 0.5
  [2/3] reference: 0.0
  [2/3] judgement: 1.0
  [2/3] suggestion: 0.5
  [3/3] reference: 0.5
  [3/3] judgement: 0.0
  [3/3] suggestion: 0.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 28 to 30...
  [1/3] reference: 0.0
  [1/3] judgement: 0.0
  [1/3] suggestion: 0.0
  [2/3] reference: 0.0
  [2/3] judgement: 0.0
  [2/3] suggestion: 0.5
  [3/3] reference: 0.5
  [3/3] judgement: 0.0
  [3/3] suggestion: 1.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 31 to 33...
  [1/3] reference: 0.5
  [1/3] judgement: 1.0
  [1/3] suggestion: 0.5
  [2/3] reference: 0.5
  [2/3] judgement: 0.5
  [2/3] suggestion: 0.5
  [3/3] reference: 0.5
  [3/3] judgement: 1.0
  [3/3] suggestion: 1.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 34 to 36...
  [1/3] reference: 0.5
  [1/3] judgement: 1.0
  [1/3] suggestion: 1.0
  [2/3] reference: 0.5
  [2/3] judgement: 1.0
  [2/3] suggestion: 1.0
  [3/3] reference: 0.5
  [3/3] judgement: 0.0
  [3/3] suggestion: 1.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 37 to 39...
  [1/3] reference: 1.0
  [1/3] judgement: 0.0
  [1/3] suggestion: 0.0
  [2/3] reference: 0.0
  [2/3] judgement: 0.5
  [2/3] suggestion: 1.0
  [3/3] reference: 0.5
  [3/3] judgement: 0.0
  [3/3] suggestion: 0.5
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 40 to 42...
  [1/3] reference: 0.5
  [1/3] judgement: 1.0
  [1/3] suggestion: 0.5
  [2/3] reference: 0.0
  [2/3] judgement: 1.0
  [2/3] suggestion: 1.0
  [3/3] reference: 0.5
  [3/3] judgement: 1.0
  [3/3] suggestion: 0.5
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

Re-running scorers for entries 43 to 45...
  [1/3] reference: 0.0
  [1/3] judgement: 1.0
  [1/3] suggestion: 0.5
  [2/3] reference: 0.5
  [2/3] judgement: 0.5
  [2/3] suggestion: 1.0
  [3/3] reference: 0.5
  [3/3] judgement: 1.0
  [3/3] suggestion: 1.0
Sleeping for 20 seconds to avoid rate limits...
------------------------------------------------

[EntryReview(index=0, input='เจ้าของบัญชีเงินฝากถึงแก่กรรม บุคคลที่อ้างว่าเป็นทายาทขอดำเนินการจัดการบัญชี เช่น ปิดบัญชีเงินฝากดังกล่าวโดยไม่ดำเนินการจัดตั้งผู้จัดการมรดกได้หรือไม่', output='ในฐานะผู้เชี่ยวชาญทางกฎหมายอาวุโสของธนาคาร ขอเรียนชี้แจงประเด็นข้อกฎหมายและแนวทางปฏิบัติกรณีเจ้าของบัญชีเงินฝากถึงแก่กรรม และทายาทขอจัดการบัญชีโดยไม่มีคำสั่งตั้งผู้จัดการมรดก ดังนี้\n\n## 1. มาตรากฎหมายที่เกี่ยวข้อง\n\nจากการตรวจสอบแหล่งข้อมูลกฎหมาย (File Store) พบมาตรากฎหมายที่เกี่ยวข้องโดยตรง ดังนี้:\n\n*   **ประมวลกฎหมายแพ่งและพาณิชย์ (กฎหมายทั่วไป)**\n    *   **มาตรา ๖๖๕** "ผู้รับฝากจำต้องคืนทรัพย์สินซึ่งรับฝากไว้นั้นให้แก่ผู้ฝาก หรือทรัพย์สินนั้นฝากในนามของผู้ใด ให้คืนแก่ผู้นั้น\n        แต่หากผู้ฝากทรัพย์ตาย ท่านให้คืนทรัพย์สินนั้นให้แก่ทายาท"\n    *   **มาตรา ๑๕๙๙** "เมื่อบุคคลใดตาย มรดกของบุคคลนั้นตกทอดแก่ทายาท\n        ทายาทอาจเสียไปซึ่งสิทธิในมรดกได้แต่โดยบทบัญญัติแห่งประมวลกฎหมายนี้หรือกฎหมายอื่น"\n    *   **มาตรา ๑๖๐๐** "ภายใต้บังคับของบทบัญญัติแห่งประมวลกฎหมายนี้ กองมรดกของผู้ตายได้แก่ทรัพย์สินทุกชนิดของผู้ตาย ตลอดทั้งสิทธิหน้าที่และความรับผิดต่าง ๆ เว้นแต่ตามกฎหมายหรือว่าโดยสภาพแล้ว เป็นการเฉพาะตัวของผู้ตายโดยแท้"\n\n*   **พระราชบัญญัติบริษัทมหาชนจำกัด พ.ศ. ๒๕๓๕ (กฎหมายเฉพาะ - อ้างอิงโดยอนุโลมในส่วนการจัดการสิทธิของผู้ถึงแก่กรรม)**\n    *   **มาตรา ๕๙** "ในกรณีที่ผู้ถือหุ้นของบริษัทตายหรือล้มละลาย อันเป็นเหตุให้บุคคลใดมีสิทธิในหุ้นนั้น ถ้าบุคคลนั้นได้นำหลักฐานที่ชอบด้วยกฎหมายมาแสดงครบถ้วนแล้วให้บริษัทลงทะเบียนและออกใบหุ้นให้ใหม่ภายในหนึ่งเดือนนับแต่วันได้รับหลักฐานครบถ้วน"\n\n---\n\n## 2. คำวินิจฉัย\n\nจากการวิเคราะห์ข้อกฎหมายและแนวบรรทัดฐานจากคำพิพากษาศาลฎีกา สามารถวินิจฉัยแยกตามประเด็นได้ดังนี้:\n\n**๑) สิทธิตามกฎหมายของทายาทต่อบัญชีเงินฝาก:**\nตาม **ป.พ.พ. มาตรา ๖๖๕ วรรคสอง** กฎหมายบัญญัติไว้อย่างชัดเจนว่า เมื่อผู้ฝากเงินถึงแก่ความตาย ธนาคารในฐานะผู้รับฝากมีหน้าที่ต้องคืนเงินฝากนั้นให้แก่ **"ทายาท"** ซึ่งสอดคล้องกับ **มาตรา ๑๕๙๙** ที่มรดก (รวมถึงสิทธิเรียกร้องในเงินฝาก) ย่อมตกทอดแก่ทายาททันทีที่เจ้ามรดกถึงแก่ความตาย ดังนั้น ในทางกฎหมาย ทายาทจึงมีสิทธิขอปิดบัญชีและรับเงินฝากคืนได้โดยไม่จำเป็นต้องมีผู้จัดการมรดกเสมอไป\n\n**๒) การใช้อ้างอิงบรรทัดฐานศาลฎีกา:**\n*   **คำพิพากษาศาลฎีกาที่ ๒๐๗๑/๒๕๖๓:** ศาลวินิจฉัยว่าตาม ป.พ.พ. มาตรา ๖๖๕ วรรคสอง เมื่อผู้ฝากตาย ธนาคารต้องคืนเงินให้ทายาท ส่วนระเบียบภายในของธนาคารที่กำหนดว่าหากเงินเกิน ๕๐,๐๐๐ บาท ต้องมีหนังสือรับรองคดีถึงที่สุด (กรณีตั้งผู้จัดการมรดก) มาแสดงนั้น เป็นเพียงระเบียบภายในเพื่อความรอบคอบของธนาคารเอง ไม่ผูกพันทายาทและเป็นการเพิ่มภาระให้ทายาทโดยไม่จำเป็น หากทายาทสามารถนำหลักฐานมาพิสูจน์จนเป็นที่พอใจแก่ธนาคารได้ ธนาคารต้องคืนเงิน หากไม่คืนถือเป็นการผิดสัญญาฝากทรัพย์\n*   **คำพิพากษาศาลฎีกาที่ ๗๒๘๓/๒๕๖๒:** ยืนยันว่าเมื่อผู้ฝากถึงแก่ความตาย ธนาคารต้องคืนเงินให้แก่ทายาทของผู้ฝากเท่านั้น การที่ธนาคารจ่ายเงินให้แก่ผู้จัดการมรดก (ซึ่งเป็นทายาทด้วย) ถือเป็นการจ่ายที่ชอบด้วยกฎหมายแล้ว\n\n**๓) สถานการณ์ที่แตกต่างกัน:**\n*   **กรณีทายาทมีหลักฐานชัดเจน:** หากทายาทสามารถแสดงหลักฐานความเป็นทายาทที่ชัดเจน (เช่น สูติบัตร ทะเบียนบ้าน มรณบัตร) และไม่มีเหตุแห่งการคัดค้าน ธนาคารสามารถพิจารณาดำเนินการให้ได้ตามสิทธิใน ป.พ.พ. มาตรา ๖๖๕\n*   **กรณีมีข้อพิพาทหรือความเสี่ยง:** หากธนาคารไม่มั่นใจว่าบุคคลที่มาแสดงตัวเป็นทายาทเพียงผู้เดียวหรือไม่ หรือมีทายาทหลายคนที่มีสิทธิร่วมกันตาม **ป.พ.พ. มาตรา ๑๗๔๕** ธนาคารมีสิทธิที่จะใช้ความระมัดระวังตามมาตรฐานวิชาชีพ (**ป.พ.พ. มาตรา ๖๕๙ วรรคสาม**) ในการขอให้จัดตั้งผู้จัดการมรดกเพื่อเป็นตัวแทนในการรับเงินและปลดเปลื้องภาระความรับผิดของธนาคาร\n\n---\n\n## 3. ข้อสรุปและข้อเสนอแนะ\n\n**สรุป:** ทายาทสามารถดำเนินการจัดการหรือปิดบัญชีเงินฝากได้โดยไม่จำเป็นต้องจัดตั้งผู้จัดการมรดก หากสามารถพิสูจน์สถานะความเป็นทายาทให้เป็นที่พอใจแก่ธนาคารได้ตามสิทธิที่กฎหมายบัญญัติไว้ใน ป.พ.พ. มาตรา ๖๖๕ วรรคสอง และตามแนวคำพิพากษาศาลฎีกาที่ ๒๐๗๑/๒๕๖๓\n\n**ข้อเสนอแนะและแนวทางปฏิบัติสำหรับธนาคาร:**\n1.  **การตรวจสอบหลักฐาน:** ธนาคารควรจัดทำรายการเอกสาร (Checklist) ที่จำเป็นสำหรับการพิสูจน์ความเป็นทายาท เช่น มรณบัตร, ทะเบียนบ้านของผู้ตายและทายาท, บัตรประชาชนทายาท, และหนังสือรับรองเครือญาติจากทางราชการ\n2.  **กำหนดเกณฑ์วงเงิน:** เพื่อบริหารความเสี่ยง ธนาคารอาจกำหนดวงเงินภายใน (เช่น ไม่เกิน ๕๐,๐๐๐ หรือ ๑๐๐,๐๐๐ บาท) ที่อนุญาตให้ทายาทโดยธรรมปิดบัญชีได้โดยไม่ต้องมีคำสั่งศาล แต่ต้องให้ทายาททุกคน (ถ้ามีหลายคน) ลงนามยินยอมและทำหนังสือสัญญาชดใช้ความเสียหาย (Indemnity Letter) ให้แก่ธนาคาร\n3.  **กรณีเงินจำนวนสูงหรือมีความซับซ้อน:** หากยอดเงินในบัญชีมีจำนวนสูงมาก หรือกรณีที่ทายาทตกลงกันไม่ได้ หรือมีเหตุอันควรสงสัยในสิทธิของทายาท ธนาคารควรแนะนำให้ทายาทไปดำเนินการร้องขอต่อศาลเพื่อตั้งผู้จัดการมรดกตาม **ป.พ.พ. มาตรา ๑๗๑๓** เพื่อความปลอดภัยทางกฎหมายของธนาคารเอง\n4.  **ข้อควรระวัง:** ธนาคารต้องระมัดระวังการจ่ายเงินให้ทายาทเพียงคนเดียวในกรณีที่มีทายาทหลายคน เพราะหากทายาทคนอื่นไม่ได้รับเงิน อาจฟ้องร้องธนาคารฐานผิดสัญญาฝากทรัพย์ได้ ดังนั้นการขอให้ทายาททุกคนมาปรากฏตัวหรือมีหนังสือมอบอำนาจที่ชัดเจนจึงเป็นสิ่งสำคัญที่สุดตามมาตรฐานวิชาชีพธนาคาร (**ป.พ.พ. มาตรา ๖๕๙ วรรคสาม**)\nSources: {\'Supreme Court Statement/ความสามารถ ผู้เยาว์/supreme_court_statement_1649_2567.docx\', \'Supreme Court Statement/ความสามารถ ผู้เยาว์/supreme_court_statement_1783_2558.docx\', \'Supreme Court Statement/ผู้จัดการมรดก ผู้ฝาก/supreme_court_statement_2071_2563.docx\', \'General Law/CCC_20251111.pdf\', \'Supreme Court Statement/ธนาคาร บัญชี/supreme_court_statement_6233_2564.docx\', \'Public Company Law/Act_Public_Company_2535_20260204.pdf\', \'Supreme Court Statement/ผู้จัดการมรดก ผู้ฝาก/supreme_court_statement_7283_2562.docx\'}', expected='## 1. มาตรากฎหมายที่เกี่ยวข้อง\nป.พ.พ:\nมาตรา ๑๗๑๓  ทายาทหรือผู้มีส่วนได้เสียหรือพนักงานอัยการจะร้องต่อศาลขอให้ตั้งผู้จัดการมรดกก็ได้ ในกรณีดังต่อไปนี้\n\n(๑) เมื่อเจ้ามรดกตาย ทายาทโดยธรรมหรือผู้รับพินัยกรรมได้สูญหายไป หรืออยู่นอกราชอาณาเขต หรือเป็นผู้เยาว์\n\n(๒) เมื่อผู้จัดการมรดกหรือทายาทไม่สามารถ หรือไม่เต็มใจที่จะจัดการ หรือมีเหตุขัดข้องในการจัดการ หรือในการแบ่งปันมรดก\n\n(๓) เมื่อข้อกำหนดพินัยกรรมซึ่งตั้งผู้จัดการมรดกไว้ไม่มีผลบังคับได้ด้วยประการใด ๆ\n\n                      การตั้งผู้จัดการมรดกนั้น ถ้ามีข้อกำหนดพินัยกรรมก็ให้ศาลตั้งตามข้อกำหนดพินัยกรรม และถ้าไม่มีข้อกำหนดพินัยกรรม ก็ให้ศาลตั้งเพื่อประโยชน์แก่กองมรดกตามพฤติการณ์ และโดยคำนึงถึงเจตนาของเจ้ามรดก แล้วแต่ศาลจะเห็นสมควร\n\nมาตรา ๑๗๑๘  บุคคลต่อไปนี้จะเป็นผู้จัดการมรดกไม่ได้\n\n(๑) ผู้ซึ่งยังไม่บรรลุนิติภาวะ\n\n(๒) บุคคลวิกลจริต หรือบุคคลซึ่งศาลสั่งให้เป็นผู้เสมือนไร้ความสามารถ\n\n(๓) บุคคลซึ่งศาลสั่งให้เป็นคนล้มละลาย\n\n๑๗๑๙  ผู้จัดการมรดกมีสิทธิและหน้าที่ที่จะทำการอันจำเป็น เพื่อให้การเป็นไปตามคำสั่งแจ้งชัดหรือโดยปริยายแห่งพินัยกรรม และเพื่อจัดการมรดกโดยทั่วไปหรือเพื่อแบ่งปันทรัพย์มรดก\n\n## 2. คำวินิจฉัย\nเนื่องจากเจ้าของบัญชีอาจมีทายาทหลายคน  และธนาคารไม่สามารถทราบได้ว่าการดำเนินการจัดการบัญชีของทายาทคนใดคนหนึ่ง หรือกลุ่มกลุ่มหนึ่งเป็นทายาททุกคนของเจ้าของบัญชีแล้วหรือไม่ จึงต้องอาศัยการดำเนินการของผู้จัดการมรดกตามคำสั่งศาลซึ่งมีหน้าที่จัดการทรัพย์มรดกตามกฎหมาย \n\n## 3. ข้อสรุปและข้อเสนอแนะ\nการจัดการทรัพย์มรดกของผู้เสียชีวิตต้องเป็นผู้จัดการมรดกตามคำสั่งศาล  หากธนาคารตกลงดำเนินการตามที่ทายาทลูกค้าร้องขอโดยไม่มีคำสั่งศาลแต่งตั้งผู้จัดการมรดกมาแสดงเป็นหลักฐาน ธนาคารอาจมีความเสี่ยงที่จะถูกฟ้องร้อง/เรียกร้องได้ หากภายหลังปรากฏว่ามีทายาทอื่นที่ได้รับการรับรองจากศาลมาแสดงตนเพื่อเรียกร้องสิทธิการจัดการเงินในบัญชีเงินฝากดังกล่าว', scorer_results=[ScorerResult(scorer_name='reference', score=0.0, choice='อ้างอิงมาตรากฎหมายไม่ถูกต้อง หรือไม่เกี่ยวข้อง', rationale="จากการเปรียบเทียบเนื้อหาในส่วน '1. มาตรากฎหมายที่เกี่ยวข้อง' ระหว่าง OUTPUT และ EXPECTED พบว่า:\n\n1. **ความถูกต้องของมาตรา:** OUTPUT อ้างอิงมาตรา ๖๖๕, ๑๕๙๙, ๑๖๐๐ และ พ.ร.บ. บริษัทมหาชนฯ มาตรา ๕๙ ซึ่ง **ไม่ตรง** กับมาตราที่ระบุใน EXPECTED เลย (EXPECTED ระบุมาตรา ๑๗๑๓, ๑๗๑๘ และ ๑๗๑๙)\n2. **ความครอบคลุม:** OUTPUT ไม่ได้ระบุมาตราสำคัญตามที่เฉลยกำหนดไว้เลยแม้แต่มาตราเดียว ทำให้เนื้อหาทางกฎหมายที่ใช้เป็นฐานในการวินิจฉัยแตกต่างจากเฉลยอย่างสิ้นเชิง\n3. **เนื้อหา:** แม้ OUTPUT จะพยายามนำเสนอแง่มุมกฎหมายอื่น (สิทธิของทายาทตามมาตรา ๖๖๕) แต่โจทย์กำหนดให้ประเมินความถูกต้องโดยเทียบกับเฉลยเป็นหลัก ซึ่งเฉลยเน้นเรื่องการตั้งผู้จัดการมรดก (มาตรา ๑๗๑๓ เป็นต้นไป) ดังนั้นการที่ OUTPUT ไม่มีการอ้างอิงกลุ่มมาตราในเฉลยเลย จึงถือว่าอ้างอิงไม่ถูกต้องตามเกณฑ์การประเมิน\n\nดังนั้น จึงสรุปได้ว่าอ้างอิงมาตรากฎหมายไม่ถูกต้องหรือไม่เกี่ยวข้องตามเฉลย"), ScorerResult(scorer_name='judgement', score=1.0, choice='ตอบได้ถูกต้อง ชัดเจน ครอบคลุม', rationale='คำตอบ (OUTPUT) มีความถูกต้อง ชัดเจน และครอบคลุมเนื้อหาทางกฎหมายได้ดีกว่าเฉลย (EXPECTED) โดยมีเหตุผลดังนี้:\n\n1. **การปรับบทกฎหมายที่ตรงประเด็นกว่า:** OUTPUT อ้างอิง ป.พ.พ. มาตรา 665 (เรื่องฝากทรัพย์) ซึ่งเป็นกฎหมายเฉพาะที่ควบคุมความสัมพันธ์ระหว่างธนาคารและลูกค้าโดยตรง ในขณะที่ EXPECTED อ้างอิงเพียงกฎหมายมรดกทั่วไป (มาตรา 1713) การที่ OUTPUT ยกมาตรา 665 มาอธิบายหน้าที่ของธนาคารในการคืนเงินแก่ทายาทเป็นการวินิจฉัยที่ถูกต้องตามหลักกฎหมายมากกว่า\n\n2. **การอ้างอิงบรรทัดฐานคำพิพากษาศาลฎีกา:** OUTPUT มีการยกคำพิพากษาศาลฎีกาที่ 2071/2563 ซึ่งวินิจฉัยประเด็นนี้ไว้โดยตรงว่า "ระเบียบธนาคารที่บังคับให้ต้องมีผู้จัดการมรดกนั้นใช้บังคับกับทายาทไม่ได้หากทายาทพิสูจน์สิทธิได้" ซึ่งเป็นการขยายความและแก้ไขความเข้าใจที่คลาดเคลื่อนจากเฉลยที่สรุปว่า "ต้อง" อาศัยผู้จัดการมรดกเพียงอย่างเดียว\n\n3. **ความครบถ้วนในแง่การบริหารความเสี่ยง:** แม้ OUTPUT จะยืนยันสิทธิของทายาทตามกฎหมาย แต่ก็ไม่ได้ละเลยประเด็นความเสี่ยงที่เฉลยระบุไว้ โดยในส่วนข้อเสนอแนะ (Section 3) ของ OUTPUT ได้ระบุแนวทางปฏิบัติที่สอดคล้องกับเฉลย คือหากมีความซับซ้อนหรือวงเงินสูง ก็ควรให้ตั้งผู้จัดการมรดกเพื่อป้องกันความเสี่ยง\n\nสรุปคือ OUTPUT ให้คำตอบที่ถูกต้องตามหลักกฎหมายและแนวคำพิพากษาปัจจุบัน (Legal Rights) พร้อมทั้งให้คำแนะนำด้านการปฏิบัติ (Risk Management) ที่ครอบคลุมเจตนารมณ์ของเฉลยอย่างครบถ้วน'), ScorerResult(scorer_name='suggestion', score=0.0, choice='ไม่ถูกต้องตามเฉลย', rationale='ผลการประเมินคือ \'ไม่ถูกต้องตามเฉลย\' โดยมีเหตุผลประกอบดังนี้:\n\n1. **ความขัดแย้งในประเด็นหลัก (Conflict in Core Principle):**\n   - **เฉลย (EXPECTED) ข้อ 3** ระบุไว้อย่างชัดเจนว่า "การจัดการทรัพย์มรดกของผู้เสียชีวิต **ต้องเป็นผู้จัดการมรดกตามคำสั่งศาล**" และเน้นย้ำความเสี่ยงหากธนาคารดำเนินการให้ทายาทโดยไม่มีคำสั่งศาล\n   - **คำตอบ (OUTPUT) ข้อ 3** สรุปว่า "ทายาทสามารถดำเนินการจัดการหรือปิดบัญชีเงินฝากได้ **โดยไม่จำเป็นต้องจัดตั้งผู้จัดการมรดก**" และเสนอแนะให้ใช้วิธีตรวจสอบเอกสารหรือทำหนังสือสัญญาชดใช้ความเสียหายแทน\n\n2. **การขัดแย้งกับเกณฑ์การประเมิน:**\n   - แม้คำตอบ (OUTPUT) จะมีการอ้างอิงคำพิพากษาศาลฎีกา (เช่น ฎ.2071/2563) ซึ่งในทางทฤษฎีกฎหมายอาจถูกต้องในมุมมองของการคุ้มครองสิทธิทายาท แต่โจทย์กำหนดให้ **ประเมินโดยเทียบกับเฉลยเป็นหลัก**\n   - คำแนะนำใน OUTPUT ที่ให้ธนาคารจ่ายเงินแก่ทายาทโดยไม่ต้องมีคำสั่งศาล (ในวงเงินที่กำหนด) ถือเป็นการให้คำแนะนำที่ **ขัดแย้งกับแนวทางปฏิบัติในเฉลย** ที่ต้องการความรัดกุมสูงสุด (Conservative Approach) โดยให้ดำเนินการผ่านผู้จัดการมรดกเท่านั้น\n\n3. **สรุป:**\n   - คำตอบ (OUTPUT) ให้ข้อสรุปและข้อเสนอแนะที่ตรงกันข้ามกับเฉลย (EXPECTED) ในสาระสำคัญเรื่องความจำเป็นของการมีผู้จัดการมรดก จึงถือว่าไม่ถูกต้องตามเฉลยที่กำหนดไว้สำหรับการประเมินนี้')], human_scores={'reference': 0.5, 'judgement': 0.5, 'suggestion': 0}, human_feedback='1. มาตรากฎหมายที่เกี่ยวข้อง : \n-มาตราที่เกี่ยวข้องไม่ครบ\n-หน้าจอที่แสดงผล แสดงมาตราที่มีหลายวรรครวมต่อกันไปเลย ไม่แยกวรรคตามป.พ.พ ทำใหห้ผู้อ่านอาจเข้าใจผิดได้ว่าอยู่ในววรคเดียวกัน\n2. คำวินิจฉัย: \n-การวินิจฉัยที่ไปในแนวทางว่าไม่ต้องมีผู้จัดการมรดกนั้น มีความเสี่ยงต่อธนาคารมากกว่า ควรวินิจฉัยไปในแนวทางให้ลูกค้าไปดำเนินการจัดตั้งผู้จัดการมรดก แล้วให้ผู้จัดการมรดกมาติดต่อธนาคาร\n3. ข้อสรุปและข้อเสนอแนะ : เพื่อปิดความเสี่ยง ต้องแนะนำธนาคารไปเลยว่าให้ผู้ที่อ้างเป็นทายาทไปดำเนินกาศาลตั้งผู้จัดการมรดก แล้วให้ผู้จัดการมรดกมาดำเนินการ', auto_scores={'reference': 0, 'judgement': 0, 'suggestion': 0}, source_file='Deposit-Gemini-3.0 Flash Legal V02', score_diff={'reference': -0.5, 'judgement': -0.5, 'suggestion': 0}, discrepancy_summary=''),

In [59]:


with open(f'docs\\KKP\\LNC\\review_results_{REVIEW_AI_PROMPT_VERSION}.json', 'w', encoding='utf-8') as f:
    res_list = [] 
    for r in reviews:
        temp_dict = copy.deepcopy(r.__dict__)
        temp_res = []

        for score in temp_dict['scorer_results']:
            temp_res.append(score.__dict__)
            # temp_res.append(score)

        temp_dict['scorer_results'] = temp_res
        res_list.append(temp_dict)

    json.dump(res_list, f, indent=4, ensure_ascii=False)

In [60]:
# with open('docs\\KKP\\LNC\\review_results_v02.json', 'r', encoding='utf-8') as f:
#     reviews = json.loads(f.read())

# reviews

In [61]:
# 3.1.2 Compare re-run scores vs human scores
total_ref_df = {} 

for scorer_name in SCORER_NAMES:
    rerun_rows = []

    for review in reviews:
        sr = review.scorer_results[0]
        rerun_rows.append({
            "entry": review.index + 1,
            "source_file": review.source_file,
            "rerun_score": sr.score,
            "original_auto": review.auto_scores.get(scorer_name),
            "human_score": review.human_scores.get(scorer_name),
        })
        # sr = review['scorer_results'][0]
        # rerun_rows.append({
        #     "entry": review['index'] + 1,
        #     "source_file": review['source_file'],
        #     "rerun_score": sr['score'],
        #     "original_auto": review['auto_scores'].get(scorer_name),
        #     "human_score": review['human_scores'].get(scorer_name),
        # })

    ref_df = pd.DataFrame(rerun_rows)
    ref_df['dif'] = ref_df['rerun_score'] - ref_df['human_score']
    total_ref_df[scorer_name] = ref_df

total_ref_df

{'reference':     entry                         source_file  rerun_score  original_auto  \
 0       1  Deposit-Gemini-3.0 Flash Legal V02          0.0            0.0
 1       2  Deposit-Gemini-3.0 Flash Legal V02          0.5            0.5
 2       3  Deposit-Gemini-3.0 Flash Legal V02          0.5            0.5
 3       1  Deposit-Gemini-3.0 Flash Legal V02          0.5            0.5
 4       2  Deposit-Gemini-3.0 Flash Legal V02          0.5            1.0
 5       3    Deposit-Gemini-3.0 Pro Legal V02          0.0            0.5
 6       1    Deposit-Gemini-3.0 Pro Legal V02          0.0            0.5
 7       2    Deposit-Gemini-3.0 Pro Legal V02          0.5            0.5
 8       3    Deposit-Gemini-3.0 Pro Legal V02          0.5            0.5
 9       1    Deposit-Gemini-3.0 Pro Legal V02          1.0            1.0
 10      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 11      3       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 12      1       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 13      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 14      3       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 15      1       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 16      2       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 17      3       HP-Gemini-3.0 Flash Legal v02          0.0            NaN
 18      1       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 19      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 20      3       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 21      1       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 22      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 23      3       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 24      1       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 25      2  Lending-Gemini-3.0 Flash Legal V02          0.0            0.0
 26      3  Lending-Gemini-3.0 Flash Legal V02          0.5            0.0
 27      1  Lending-Gemini-3.0 Flash Legal V02          0.0            0.5
 28      2  Lending-Gemini-3.0 Flash Legal V02          0.0            0.5
 29      3  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 30      1  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 31      2  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 32      3  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 33      1  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 34      2  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 35      3  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 36      1  Lending-Gemini-3.0 Flash Legal V02          1.0            1.0
 37      2  Lending-Gemini-3.0 Flash Legal V02          0.0            1.0
 38      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 39      1  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 40      2  Lending-Gemini-3.0 Flash Legal V02          0.0            1.0
 41      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 42      1  Lending-Gemini-3.0 Flash Legal V02          0.0            1.0
 43      2  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 44      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0

     human_score  dif
 0           0.5 -0.5
 1           0.5  0.0
 2           0.5  0.0
 3           0.0  0.5
 4           0.5  0.0
 5           0.5 -0.5
 6           0.5 -0.5
 7           0.0  0.5
 8           0.5  0.0
 9           0.5  0.5
 10          1.0  0.0
 11          1.0  0.0
 12          1.0  0.0
 13          1.0  0.0
 14          1.0 -0.5
 15          1.0  0.0
 16          0.0  0.5
 17          0.0  0.0
 18          0.0  0.5
 19          0.0  1.0
 20          0.0  0.5
 21          0.0  1.0
 22          0.0  1.0
 23          0.0  0.5
 24          0.0  0.5
 25          0.0  0.0
 26          0.0  0.5
 27          0.5 -0.5
 28          0.0  0.0
 29          0.5  0.0
 30          0.5  0.0
 31          0.5  0.0
 32          0.0  0.5
 33          0.5  0.0
 34          0.5  0.0
 35          0.0  0.5
 36          0.5  0.5
 37          0.0  0.0
 38          0.0  0.5
 39          0.0  0.5
 40          0.5 -0.5
 41          0.5  0.0
 42          0.0  0.0
 43          0.0  0.5
 44          0.0  0.5  ,
 'judgement':     entry                         source_file  rerun_score  original_auto  \
 0       1  Deposit-Gemini-3.0 Flash Legal V02          0.0            0.0
 1       2  Deposit-Gemini-3.0 Flash Legal V02          0.5            0.0
 2       3  Deposit-Gemini-3.0 Flash Legal V02          0.5            0.5
 3       1  Deposit-Gemini-3.0 Flash Legal V02          0.5            1.0
 4       2  Deposit-Gemini-3.0 Flash Legal V02          0.5            1.0
 5       3    Deposit-Gemini-3.0 Pro Legal V02          0.0            0.0
 6       1    Deposit-Gemini-3.0 Pro Legal V02          0.0            0.0
 7       2    Deposit-Gemini-3.0 Pro Legal V02          0.5            0.5
 8       3    Deposit-Gemini-3.0 Pro Legal V02          0.5            1.0
 9       1    Deposit-Gemini-3.0 Pro Legal V02          1.0            1.0
 10      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 11      3       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 12      1       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 13      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 14      3       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 15      1       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 16      2       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 17      3       HP-Gemini-3.0 Flash Legal v02          0.0            NaN
 18      1       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 19      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 20      3       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 21      1       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 22      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 23      3       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 24      1       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 25      2  Lending-Gemini-3.0 Flash Legal V02          0.0            0.0
 26      3  Lending-Gemini-3.0 Flash Legal V02          0.5            0.0
 27      1  Lending-Gemini-3.0 Flash Legal V02          0.0            0.0
 28      2  Lending-Gemini-3.0 Flash Legal V02          0.0            0.5
 29      3  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 30      1  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 31      2  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 32      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 33      1  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 34      2  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 35      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 36      1  Lending-Gemini-3.0 Flash Legal V02          1.0            0.0
 37      2  Lending-Gemini-3.0 Flash Legal V02          0.0            0.5
 38      3  Lending-Gemini-3.0 Flash Legal V02          0.5            0.5
 39      1  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 40      2  Lending-Gemini-3.0 Flash Legal V02          0.0            1.0
 41      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 42      1  Lending-Gemini-3.0 Flash Legal V02          0.0            1.0
 43      2  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 44      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0

     human_score  dif
 0           0.5 -0.5
 1           0.5  0.0
 2           1.0 -0.5
 3           0.0  0.5
 4           1.0 -0.5
 5           0.0  0.0
 6           0.0  0.0
 7           0.0  0.5
 8           0.5  0.0
 9           1.0  0.0
 10          0.0  1.0
 11          1.0  0.0
 12          1.0  0.0
 13          1.0  0.0
 14          1.0 -0.5
 15          1.0  0.0
 16          0.0  0.5
 17          1.0 -1.0
 18          1.0 -0.5
 19          1.0  0.0
 20          1.0 -0.5
 21          1.0  0.0
 22          1.0  0.0
 23          0.0  0.5
 24          0.0  0.5
 25          0.0  0.0
 26          0.0  0.5
 27          0.0  0.0
 28          0.0  0.0
 29          0.0  0.5
 30          0.5  0.0
 31          0.5  0.0
 32          0.0  0.5
 33          0.0  0.5
 34          0.5  0.0
 35          0.0  0.5
 36          0.5  0.5
 37          0.0  0.0
 38          0.5  0.0
 39          0.0  0.5
 40          0.5 -0.5
 41          1.0 -0.5
 42          0.0  0.0
 43          0.0  0.5
 44          1.0 -0.5  ,
 'suggestion':     entry                         source_file  rerun_score  original_auto  \
 0       1  Deposit-Gemini-3.0 Flash Legal V02          0.0            0.0
 1       2  Deposit-Gemini-3.0 Flash Legal V02          0.5            0.0
 2       3  Deposit-Gemini-3.0 Flash Legal V02          0.5            1.0
 3       1  Deposit-Gemini-3.0 Flash Legal V02          0.5            1.0
 4       2  Deposit-Gemini-3.0 Flash Legal V02          0.5            1.0
 5       3    Deposit-Gemini-3.0 Pro Legal V02          0.0            0.0
 6       1    Deposit-Gemini-3.0 Pro Legal V02          0.0            0.0
 7       2    Deposit-Gemini-3.0 Pro Legal V02          0.5            0.5
 8       3    Deposit-Gemini-3.0 Pro Legal V02          0.5            1.0
 9       1    Deposit-Gemini-3.0 Pro Legal V02          1.0            1.0
 10      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 11      3       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 12      1       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 13      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 14      3       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 15      1       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 16      2       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 17      3       HP-Gemini-3.0 Flash Legal v02          0.0            NaN
 18      1       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 19      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 20      3       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 21      1       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 22      2       HP-Gemini-3.0 Flash Legal v02          1.0            NaN
 23      3       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 24      1       HP-Gemini-3.0 Flash Legal v02          0.5            NaN
 25      2  Lending-Gemini-3.0 Flash Legal V02          0.0            0.0
 26      3  Lending-Gemini-3.0 Flash Legal V02          0.5            0.0
 27      1  Lending-Gemini-3.0 Flash Legal V02          0.0            0.0
 28      2  Lending-Gemini-3.0 Flash Legal V02          0.0            1.0
 29      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 30      1  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 31      2  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 32      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 33      1  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 34      2  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 35      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 36      1  Lending-Gemini-3.0 Flash Legal V02          1.0            0.0
 37      2  Lending-Gemini-3.0 Flash Legal V02          0.0            0.5
 38      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 39      1  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 40      2  Lending-Gemini-3.0 Flash Legal V02          0.0            1.0
 41      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 42      1  Lending-Gemini-3.0 Flash Legal V02          0.0            1.0
 43      2  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0
 44      3  Lending-Gemini-3.0 Flash Legal V02          0.5            1.0

     human_score  dif
 0           0.0  0.0
 1           0.5  0.0
 2           0.5  0.0
 3           1.0 -0.5
 4           1.0 -0.5
 5           0.0  0.0
 6           0.0  0.0
 7           0.5  0.0
 8           0.5  0.0
 9           1.0  0.0
 10          0.0  1.0
 11          1.0  0.0
 12          1.0  0.0
 13          1.0  0.0
 14          1.0 -0.5
 15          0.0  1.0
 16          0.0  0.5
 17          0.0  0.0
 18          1.0 -0.5
 19          1.0  0.0
 20          0.0  0.5
 21          1.0  0.0
 22          1.0  0.0
 23          0.0  0.5
 24          0.0  0.5
 25          1.0 -1.0
 26          0.0  0.5
 27          0.0  0.0
 28          0.5 -0.5
 29          0.0  0.5
 30          0.5  0.0
 31          0.5  0.0
 32          0.0  0.5
 33          0.5  0.0
 34          1.0 -0.5
 35          1.0 -0.5
 36          0.5  0.5
 37          0.5 -0.5
 38          0.5  0.0
 39          0.5  0.0
 40          0.5 -0.5
 41          0.5  0.0
 42          0.5 -0.5
 43          0.5  0.0
 44          1.0 -0.5  }

In [62]:
for scorer_name in SCORER_NAMES:
    print(f"{scorer_name}: {total_ref_df[scorer_name]['dif'].abs().sum()}")

reference: 14.0
judgement: 13.0
suggestion: 12.5

In [63]:
total_ref_df['reference']

,entry,source_file,rerun_score,original_auto,human_score,dif
0,1,Deposit-Gemini-3.0 Flash Legal V02,0.0,0.0,0.5,-0.5
1,2,Deposit-Gemini-3.0 Flash Legal V02,0.5,0.5,0.5,0.0
2,3,Deposit-Gemini-3.0 Flash Legal V02,0.5,0.5,0.5,0.0
3,1,Deposit-Gemini-3.0 Flash Legal V02,0.5,0.5,0.0,0.5
4,2,Deposit-Gemini-3.0 Flash Legal V02,0.5,1.0,0.5,0.0
5,3,Deposit-Gemini-3.0 Pro Legal V02,0.0,0.5,0.5,-0.5
6,1,Deposit-Gemini-3.0 Pro Legal V02,0.0,0.5,0.5,-0.5
7,2,Deposit-Gemini-3.0 Pro Legal V02,0.5,0.5,0.0,0.5
8,3,Deposit-Gemini-3.0 Pro Legal V02,0.5,0.5,0.5,0.0
9,1,Deposit-Gemini-3.0 Pro Legal V02,1.0,1.0,0.5,0.5
10,2,HP-Gemini-3.0 Flash Legal v02,1.0,NaN,1.0,0.0
11,3,HP-Gemini-3.0 Flash Legal v02,1.0,NaN,1.0,0.0
12,1,HP-Gemini-3.0 Flash Legal v02,1.0,NaN,1.0,0.0
13,2,HP-Gemini-3.0 Flash Legal v02,1.0,NaN,1.0,0.0
14,3,HP-Gemini-3.0 Flash Legal v02,0.5,NaN,1.0,-0.5
15,1,HP-Gemini-3.0 Flash Legal v02,1.0,NaN,1.0,0.0
16,2,HP-Gemini-3.0 Flash Legal v02,0.5,NaN,0.0,0.5
17,3,HP-Gemini-3.0 Flash Legal v02,0.0,NaN,0.0,0.0
18,1,HP-Gemini-3.0 Flash Legal v02,0.5,NaN,0.0,0.5
19,2,HP-Gemini-3.0 Flash Legal v02,1.0,NaN,0.0,1.0
20,3,HP-Gemini-3.0 Flash Legal v02,0.5,NaN,0.0,0.5
21,1,HP-Gemini-3.0 Flash Legal v02,1.0,NaN,0.0,1.0
22,2,HP-Gemini-3.0 Flash Legal v02,1.0,NaN,0.0,1.0
23,3,HP-Gemini-3.0 Flash Legal v02,0.5,NaN,0.0,0.5
24,1,HP-Gemini-3.0 Flash Legal v02,0.5,NaN,0.0,0.5
25,2,Lending-Gemini-3.0 Flash Legal V02,0.0,0.0,0.0,0.0
26,3,Lending-Gemini-3.0 Flash Legal V02,0.5,0.0,0.0,0.5
27,1,Lending-Gemini-3.0 Flash Legal V02,0.0,0.5,0.5,-0.5
28,2,Lending-Gemini-3.0 Flash Legal V02,0.0,0.5,0.0,0.0
29,3,Lending-Gemini-3.0 Flash Legal V02,0.5,0.5,0.5,0.0
30,1,Lending-Gemini-3.0 Flash Legal V02,0.5,0.5,0.5,0.0
31,2,Lending-Gemini-3.0 Flash Legal V02,0.5,0.5,0.5,0.0
32,3,Lending-Gemini-3.0 Flash Legal V02,0.5,0.5,0.0,0.5
33,1,Lending-Gemini-3.0 Flash Legal V02,0.5,0.5,0.5,0.0
34,2,Lending-Gemini-3.0 Flash Legal V02,0.5,0.5,0.5,0.0
35,3,Lending-Gemini-3.0 Flash Legal V02,0.5,0.5,0.0,0.5
36,1,Lending-Gemini-3.0 Flash Legal V02,1.0,1.0,0.5,0.5
37,2,Lending-Gemini-3.0 Flash Legal V02,0.0,1.0,0.0,0.0
38,3,Lending-Gemini-3.0 Flash Legal V02,0.5,1.0,0.0,0.5
39,1,Lending-Gemini-3.0 Flash Legal V02,0.5,1.0,0.0,0.5
40,2,Lending-Gemini-3.0 Flash Legal V02,0.0,1.0,0.5,-0.5
41,3,Lending-Gemini-3.0 Flash Legal V02,0.5,1.0,0.5,0.0
42,1,Lending-Gemini-3.0 Flash Legal V02,0.0,1.0,0.0,0.0
43,2,Lending-Gemini-3.0 Flash Legal V02,0.5,1.0,0.0,0.5
44,3,Lending-Gemini-3.0 Flash Legal V02,0.5,1.0,0.0,0.5

In [ ]:
# for scorer_name in SCORER_NAMES:
    # print(scorer_name, '\n')
    # print(total_ref_df[scorer_name].groupby(['source_file']).agg({'dif': lambda x: x.abs().sum(), ''}))

SyntaxError: ':' expected after dictionary key (1630486363.py, line 3)

## Discrepancies Analysis

In [65]:
review_results = [] 

for review in reviews:
    review_results.append({
        "input": review.input,
        "output": review.output,
        "expected": review.expected, 
        "human_scores": review.human_scores,
        "auto_scores": review.auto_scores,
        "human_feedback": review.human_feedback,
        "scorer_rationale": "\n".join([result.rationale for result in review.scorer_results])}
    )

# review_results

In [66]:
dif_response = client.models.generate_content(model="gemini-3-pro-preview", 
                        contents=f"""
                        INSTRUCTION:
                        คุณคือ Agent ในการวิเคราะห์ feedback ที่มนุษย์ให้ไว้สำหรับคำตอบของโมเดลตอบคำถามทางกฎหมายของธนาคาร โดยประกอบด้วยการให้คะแนน 3 ส่วน
                        1. reference - การให้คะแนนความถูกต้องของกฎหมายอ้างอิง โดยจำเป็นต้องบอกกฎหมายให้ถูกต้องและครบถ้วนตามที่มนุษย์ให้ไว้ เกณฑ์การให้คะแนนดังนี้
                            1.1 "อ้างอิงมาตรากฎหมายถูกต้องและครอบคลุมตามเฉลย": 1.0
                            1.2 "อ้างอิงมาตรากฎหมายไม่ถูกต้อง หรือไม่เกี่ยวข้อง": 0.0
                            1.3 "อ้างอิงมาตรากฎหมายถูกต้อง แต่ไม่ครอบคลุม มีมาตราสำคัญตกหล่น": 0.5

                        2. judgement - การให้คะแนนความสมเหตุสมผลของการวินิจฉัย โดยต้องสอดคล้องกับกฎหมายอ้างอิงที่ให้ไว้ และต้องมีเหตุผลสนับสนุนที่ชัดเจน เกณฑ์การให้คะแนนดังนี้
                        
                            2.1 "ตอบได้ถูกต้อง ชัดเจน ครอบคลุม": 1.0
                            2.2 "ไม่ถูกต้องตามเฉลย": 0.0
                            2.3 "ตอบได้ถูกต้อง แต่ไม่ครอบคลุม มีเนื้อหาสำคัญตกหล่น": 0.5
                        3. suggestion - การให้คะแนนความถูกต้องและความเหมาะสมของข้อสรุปและคำแนะนำ โดยต้องสอดคล้องกับกฎหมายอ้างอิงและการวินิจฉัยที่ให้ไว้ และต้องมีเหตุผลสนับสนุนที่ชัดเจน และต้องเป็นประโยชน์ต่อธนาคาร เกณฑ์การให้คะแนนดังนี้

                            3.1 "ตอบได้ถูกต้อง ชัดเจน ครอบคลุม ให้ข้อเสนอแนะที่เป็นไปได้จริง": 1.0
                            3.2 "ไม่ถูกต้องตามเฉลย": 0.0
                            3.3 "ตอบได้ถูกต้อง แต่ไม่ครอบคลุม มีเนื้อหาสำคัญตกหล่น": 0.5

                        จงสรุปข้อแตกต่างของ human_feedback และ scorer_rationale ของแต่ละคะแนน reference, judgement, suggestion 
                        รวมถึง human_score และ scorer_score จากข้อมูลอ้างอิงทั้งหมด ทุก records ว่ามีความแตกต่างกันอย่างไรบ้าง และมีจุดไหนที่ scorer_rationale ไม่สอดคล้องกับ human_feedback บ้าง
                        
                        IMPORTANT: 
                        - เน้นที่การให้คะแนนที่ไม่ตรงกับมนุษย์เป็นหลัก และวิเคราะห์ว่าทำไมโมเดลถึงให้คะแนนแบบนั้น โดยอิงจาก scorer_rationale ที่โมเดลให้มา เที่ยบกับ human_feedback ที่มนุษย์ให้มา
                        - สรุปเป็นภาพรวมโดยไม่ต้องลงรายละเอียดของแต่ละ record แต่ให้สรุปแนวโน้มและ pattern ที่พบจากข้อมูลทั้งหมด

                        โดยอิงจากข้อมูลนี้: {review_results}
                        โดยกำหนดให้:
                        - input คือคำถามทางกฎหมายที่ให้โมเดลตอบตามข้อมูลที่มีอยู่ใน File Store
                        - output คือคำตอบที่โมเดลให้มา
                        - expected คือคำตอบที่ถูกต้องหรือคำตอบที่มนุษย์คาดหวัง
                        - human_scores คือคะแนนที่มนุษย์ให้ไว้สำหรับคำตอบของโมเดลในแต่ละส่วน reference, judgement, suggestion
                        - auto_scores คือคะแนนที่โมเดลให้ไว้สำหรับคำตอบของโมเดลในแต่ละส่วน reference, judgement, suggestion
                        - human_feedback คือ feedback ที่มนุษย์ให้ไว้สำหรับคำตอบของโมเดล
                        - scorer_rationale คือเหตุผลที่โมเดลให้มาสำหรับคะแนนที่ได้
                            """,
                            
                config=types.GenerateContentConfig(
                    temperature=0
                ),)

In [67]:
print(dif_response.text)

สรุปข้อแตกต่างระหว่าง **Human Feedback** และ **Scorer Rationale** รวมถึงคะแนนที่ได้รับ จากการวิเคราะห์ข้อมูลทั้งหมด พบแนวโน้มและ Pattern ที่สำคัญดังนี้:

### ภาพรวม (Overview)
โดยภาพรวม **Scorer (AI)** มักจะให้คะแนน **สูงกว่า** Human (มนุษย์) ในทุกหมวด (Reference, Judgement, Suggestion) อย่างมีนัยสำคัญ โดย Scorer มักมองว่าคำตอบมีความถูกต้องและสมเหตุสมผลในตัวเอง (Self-consistent) หรือถูกต้องตามหลักทฤษฎีกฎหมายทั่วไป ในขณะที่ Human จะตรวจโดยยึด **"เฉลย (Expected)"** เป็นเกณฑ์ตายตัว และเน้นความถูกต้องในเชิงปฏิบัติงานธนาคาร (Banking Practice) ความแม่นยำของตัวอักษร (Verbatim) และความครบถ้วนของประเด็นที่กำหนดไว้

---

### 1. Reference (การอ้างอิงกฎหมาย)

**ข้อแตกต่างสำคัญ:**
*   **ความถูกต้องทุกตัวอักษร (Verbatim Check):**
    *   **Human:** เคร่งครัดมาก หากมีการตัดทอนเนื้อหา (ใช้เครื่องหมาย ...), การสรุปความเองโดยไม่ยกตัวบทมาทั้งหมด, การพิมพ์ผิด, การใช้ถ้อยคำกฎหมายเก่า (เช่น "สามีภริยา" แทน "คู่สมรส"), หรือการจัดรูปแบบย่อหน้าไม่ตรงกับต้นฉบับ (ไม่แยกวรรค) Human จะหักคะแนนทันที หรือให้ 0
    *   **Scorer:** มักให้คะแนนเต็ม (1.0) หรือเกือบเต็ม หากเลขมาตราถูกต้อง แม้เนื้อหาข้างในจะมีการตัดทอน, มีคำผิดเล็กน้อย, หรือใช้ถ้อยคำที่ไม่ตรงกับเฉลยเป๊ะๆ Scorer มักมองข้ามความผิดพลาดเรื่องรูปแบบ (Formatting) และความแม่นยำระดับคำ (Wording)
*   **มาตราที่เกี่ยวข้อง (Relevance & Completeness):**
    *   **Human:** หากมีมาตราที่ไม่เกี่ยวข้อง (Noise) ปนมา หรือขาดมาตราสำคัญที่ระบุในเฉลย Human จะหักคะแนน
    *   **Scorer:** มักไม่หักคะแนนหากมีมาตราเกินมา (มองว่าเป็นบริบทเสริม) และบางครั้งให้คะแนนเต็มแม้จะขาดมาตราสำคัญบางมาตราไป หากมาตราหลักยังอยู่

**จุดที่ Rationale ไม่สอดคล้อง:**
*   Scorer มักระบุว่า "อ้างอิงถูกต้องครบถ้วน" ทั้งที่ Human Feedback ระบุชัดเจนว่า "เนื้อหามาตราไม่ครบ/ตัดทอน" หรือ "อ้างมาตราผิด/ไม่เกี่ยวข้อง"

---

### 2. Judgement (คำวินิจฉัย)

**ข้อแตกต่างสำคัญ:**
*   **ธงคำตอบและการปรับบทกฎหมาย (Legal Reasoning):**
    *   **Human:** ยึดตาม "ธง" ของเฉลยอย่างเคร่งครัด โดยเฉพาะในประเด็นที่มีความละเอียดอ่อนทางกฎหมาย เช่น การแปลงหนี้ใหม่ (Novation) vs การขยายเวลา (Extension of Time) หรือ การตีความแบบระมัดระวัง (Conservative) ในบริบทธนาคาร หาก Model ตอบผิดธง หรือใช้หลักกฎหมายผิดประเภท (แม้ผลลัพธ์จะคล้ายกัน) Human จะให้ 0
    *   **Scorer:** มักให้คะแนนสูง (1.0) หากคำตอบดูมีเหตุผลรองรับในตัวเอง (Logical) และมีการอ้างอิงกฎหมายประกอบ แม้ว่าบทสรุปจะขัดแย้งกับเฉลยก็ตาม (เช่น กรณีผู้ถือหุ้นค้ำประกัน หรือ กรณีแปลงหนี้ OD เป็น TL) Scorer มักไม่สามารถตรวจจับความผิดพลาดในการปรับบทกฎหมายที่ซับซ้อนได้
*   **การอ้างอิงคำพิพากษาฎีกา (Case Law):**
    *   **Human:** หากมีการอ้างอิงเลขฎีกาที่ไม่เกี่ยวข้องกับเนื้อหา (Hallucination หรือ Irrelevant Citation) Human จะถือว่าเป็นข้อผิดพลาดร้ายแรง
    *   **Scorer:** มักมองข้ามความถูกต้องของเลขฎีกา หรือมองว่าเป็นการเทียบเคียงที่ยอมรับได้ จึงยังคงให้คะแนนสูง

**จุดที่ Rationale ไม่สอดคล้อง:**
*   Scorer มักให้เหตุผลว่า "คำตอบถูกต้องและชัดเจนกว่าเฉลย" หรือ "มีการขยายความที่ดี" ในขณะที่ Human มองว่า "วินิจฉัยผิดประเด็น" หรือ "ขัดแย้งกับแนวปฏิบัติของธนาคาร"

---

### 3. Suggestion (ข้อสรุปและข้อเสนอแนะ)

**ข้อแตกต่างสำคัญ:**
*   **ความเฉพาะเจาะจง (Specificity vs Generic):**
    *   **Human:** ต้องการคำแนะนำที่ระบุ **Keyword** หรือ **ขั้นตอนปฏิบัติ** ที่เฉพาะเจาะจงตามเฉลย (เช่น ต้องระบุชื่อหน่วยงาน "สำนักงานอัยการพิเศษ...", ต้องระบุตัวเลข "20 วัน", ต้องระบุชื่อเอกสาร "หนังสือยินยอม") หากตอบเป็นหลักการกว้างๆ จะได้คะแนนน้อย
    *   **Scorer:** ให้คะแนนเต็ม (1.0) หากคำแนะนำนั้นเป็นคำแนะนำทางกฎหมายที่ถูกต้องทั่วไป (Generic Legal Advice) และดูเป็นประโยชน์ แม้จะขาดรายละเอียดเฉพาะเจาะจงที่เฉลยต้องการก็ตาม
*   **ความสอดคล้องกับเฉลย:**
    *   **Human:** หากคำวินิจฉัยผิด ข้อเสนอแนะมักจะผิดตามไปด้วย หรือหากเสนอแนะสิ่งที่เฉลยบอกว่า "ทำไม่ได้" (เช่น แนะนำวิธีเลี่ยงกฎหมาย หรือวิธีที่มีความเสี่ยงสูง) จะถูกหักคะแนน
    *   **Scorer:** แยกส่วนการให้คะแนน บางครั้ง Judgement ผิด แต่ให้ Suggestion เต็ม เพราะมองว่าคำแนะนำในส่วนนั้น (เช่น ให้ตรวจสอบเอกสาร) เป็นสิ่งที่ถูกต้องในตัวมันเอง

**จุดที่ Rationale ไม่สอดคล้อง:**
*   Scorer มักระบุว่า "ให้ข้อเสนอแนะที่เป็นไปได้จริงและครอบคลุม" ในขณะที่ Human Feedback ระบุว่า "ขาดข้อเสนอแนะเรื่อง..." หรือ "คำแนะนำไม่ตรงกับคำถาม"

---

### สรุปแนวโน้มคะแนน (Score Trend)

*   **Human Score:** มีแนวโน้ม **ต่ำ (0 หรือ 0.5)** ในหลายข้อที่ Model ตอบไม่ตรงกับเฉลยแบบเป๊ะๆ หรือมีจุดผิดพลาดเล็กน้อยในสายตานักกฎหมาย/นายธนาคาร
*   **Scorer Score:** มีแนวโน้ม **สูง (0.5 หรือ 1.0)** โดยมักจะ Overestimate คุณภาพของคำตอบ เนื่องจากไม่สามารถตรวจสอบความถูกต้องของเนื้อหากฎหมายเชิงลึก (Legal Accuracy) และบริบทเฉพาะของธนาคาร (Banking Context) ได้ดีเท่ามนุษย์

**สรุปสั้นๆ:** Scorer ตรวจจับความ "สมเหตุสมผลทางภาษา" ได้ดี แต่ล้มเหลวในการตรวจจับ "ความถูกต้องทางเทคนิคกฎหมายและระเบียบปฏิบัติ" ที่มนุษย์ให้ความสำคัญสูงสุด

## Suggest Prompt Edit

In [ ]:
from skill import load_prompt

reference_prompt = load_prompt("eval_scorer", EVAL_AI_MODEL, "legal_reference_scorer", EVAL_AI_PROMPT_VERSION)
judge_prompt = load_prompt("eval_scorer", EVAL_AI_MODEL, "legal_judgement_scorer", EVAL_AI_PROMPT_VERSION)
suggestion_prompt = load_prompt("eval_scorer", EVAL_AI_MODEL, "legal_suggestion_scorer", EVAL_AI_PROMPT_VERSION)

In [69]:
suggest_change_response = client.models.generate_content(model="gemini-3-pro-preview", 
                        contents=f"""
                        INSTRUCTION:
                        คุณคือ Agent ในการแนะนำการปรับปรุง prompt จากความแตกต่างของ feedback ที่มนุษย์ให้ไว้สำหรับคำตอบของโมเดลตอบคำถามทางกฎหมายของธนาคาร โดยประกอบด้วย prompt ของ scorer การให้คะแนน 3 ส่วน
                        1. reference - การให้คะแนนความถูกต้องของกฎหมายอ้างอิง โดยจำเป็นต้องบอกกฎหมายให้ถูกต้องและครบถ้วนตามที่มนุษย์ให้ไว้ เกณฑ์การให้คะแนนดังนี้
                            1.1 "อ้างอิงมาตรากฎหมายถูกต้องและครอบคลุมตามเฉลย": 1.0
                            1.2 "อ้างอิงมาตรากฎหมายไม่ถูกต้อง หรือไม่เกี่ยวข้อง": 0.0
                            1.3 "อ้างอิงมาตรากฎหมายถูกต้อง แต่ไม่ครอบคลุม มีมาตราสำคัญตกหล่น": 0.5

                        2. judgement - การให้คะแนนความสมเหตุสมผลของการวินิจฉัย โดยต้องสอดคล้องกับกฎหมายอ้างอิงที่ให้ไว้ และต้องมีเหตุผลสนับสนุนที่ชัดเจน เกณฑ์การให้คะแนนดังนี้
                        
                            2.1 "ตอบได้ถูกต้อง ชัดเจน ครอบคลุม": 1.0
                            2.2 "ไม่ถูกต้องตามเฉลย": 0.0
                            2.3 "ตอบได้ถูกต้อง แต่ไม่ครอบคลุม มีเนื้อหาสำคัญตกหล่น": 0.5
                        3. suggestion - การให้คะแนนความถูกต้องและความเหมาะสมของข้อสรุปและคำแนะนำ โดยต้องสอดคล้องกับกฎหมายอ้างอิงและการวินิจฉัยที่ให้ไว้ และต้องมีเหตุผลสนับสนุนที่ชัดเจน และต้องเป็นประโยชน์ต่อธนาคาร เกณฑ์การให้คะแนนดังนี้

                            3.1 "ตอบได้ถูกต้อง ชัดเจน ครอบคลุม ให้ข้อเสนอแนะที่เป็นไปได้จริง": 1.0
                            3.2 "ไม่ถูกต้องตามเฉลย": 0.0
                            3.3 "ตอบได้ถูกต้อง แต่ไม่ครอบคลุม มีเนื้อหาสำคัญตกหล่น": 0.5
                            
                        จงสรุปข้อแตกต่างของ human_feedback และ scorer_rationale ของแต่ละคะแนน reference, judgement, suggestion ว่ามีความแตกต่างกันอย่างไรบ้าง และมีจุดไหนที่ scorer_rationale ไม่สอดคล้องกับ human_feedback บ้าง

                        โดยอิงจากข้อมูลนี้: 
                        - reference scorer prompt: {reference_prompt}
                        - judgement scorer prompt: {judge_prompt}
                        - suggestion scorer prompt: {suggestion_prompt}
                        - สรุปความแตกต่างที่พบ: {dif_response.text}

                        OUTPUT: JSON ที่มี key เป็น "reference", "judgement", "suggestion" และ value เป็นคำแนะนำในการปรับปรุง prompt สำหรับแต่ละ scorer โดยต้องระบุให้ชัดเจนว่าควรปรับปรุงตรงไหนของ prompt และปรับปรุงอย่างไรเพื่อให้ scorer ให้คะแนนที่สอดคล้องกับ human_feedback มากขึ้น
                        """,
                            
                config=types.GenerateContentConfig(
                    temperature=0
                ),)
print(suggest_change_response.text)

```json
{
  "reference": "ควรปรับปรุง Prompt ให้มีความเคร่งครัดเรื่อง 'ความถูกต้องระดับตัวอักษร (Verbatim)' และ 'รูปแบบ (Formatting)' มากขึ้น โดยเพิ่มคำสั่งดังนี้:\n1. เพิ่มเงื่อนไขให้ตรวจสอบการคัดลอกตัวบทกฎหมายว่าต้อง 'ครบถ้วนทุกตัวอักษร' ห้ามมีการตัดทอน (Truncation), ห้ามใช้เครื่องหมายละความ (...), และห้ามสรุปความเอง (Paraphrasing) หากพบให้หักคะแนนทันที\n2. ระบุให้ตรวจสอบความถูกต้องของถ้อยคำเฉพาะทาง (Wording) เช่น 'คู่สมรส' vs 'สามีภริยา' ต้องตรงตามฉบับกฎหมายที่อ้างอิง\n3. เพิ่มเกณฑ์การหักคะแนนหากมีการอ้างอิงมาตราที่ไม่เกี่ยวข้อง (Irrelevant/Noise) ปะปนเข้ามา หรือการจัดรูปแบบย่อหน้าไม่ตรงกับต้นฉบับ\n4. เปลี่ยนคำสั่งจาก 'ตรวจสอบว่าครอบคลุม' เป็น 'ตรวจสอบเทียบกับเฉลยแบบคำต่อคำ (Word-for-word comparison)'",
  "judgement": "ควรปรับปรุง Prompt ให้ลดน้ำหนักของ 'ความสมเหตุสมผลในตัวเอง (Self-consistency)' และเน้น 'ความถูกต้องตามธงของเฉลย (Adherence to Expected Key)' โดยเพิ่มคำสั่งดังนี้:\n1. ระบุชัดเจนว่า 'ห้ามให้คะแนนความสมเหตุสมผล หากข้อสรุป (Conclusion) หรือธงคำตอบขัดแย้งกับเฉลย' แม้ว่าคำตอบจะดูมีตรรกะก็ตาม\n2. เพิ่มคำสั่งให้ตรวจสอบ 'ประเภทของหลักกฎหมาย' (Legal Concept) ว่าตรงกันหรือไม่ (เช่น การแปลงหนี้ใหม่ vs การขยายเวลา) หากใช้หลักผิดต้องได้ 0\n3. เน้นย้ำเรื่อง 'บริบทธนาคาร (Banking Context)' ว่าต้องวินิจฉัยแบบระมัดระวัง (Conservative) ตามเฉลย ห้ามยอมรับการตีความที่เสี่ยงหรือแตกต่างจากแนวปฏิบัติที่ระบุในเฉลย\n4. สั่งให้ตรวจสอบเลขฎีกา (Case Law) ว่าต้องตรงกับเฉลยเท่านั้น หากอ้างอิงฎีกาอื่นที่ไม่เกี่ยวข้องให้ถือว่าเป็นข้อผิดพลาด",
  "suggestion": "ควรปรับปรุง Prompt ให้เน้น 'ความเฉพาะเจาะจง (Specificity)' และ 'การนำไปใช้จริงในบริบทธนาคาร' โดยเพิ่มคำสั่งดังนี้:\n1. กำหนดให้ตรวจสอบหา 'Keywords สำคัญ' ที่ปรากฏในเฉลย เช่น ตัวเลขวันเวลา (20 วัน), ชื่อหน่วยงานเฉพาะ (สำนักงานอัยการ...), หรือชื่อเอกสาร หากตอบกว้างๆ (Generic) โดยไม่มี Keyword เหล่านี้ ให้หักคะแนน\n2. เพิ่มเงื่อนไขความสัมพันธ์ระหว่างข้อ: 'หากคำวินิจฉัย (ข้อ 2) ผิดพลาด ข้อเสนอแนะ (ข้อ 3) ควรถูกหักคะแนนด้วย' เนื่องจากคำแนะนำจะตั้งอยู่บนพื้นฐานที่ผิด\n3. ระบุให้ตรวจสอบว่าข้อเสนอแนะนั้น 'ขัดแย้งกับกฎระเบียบธนาคาร' หรือไม่ โดยยึดเฉลยเป็นหลัก ห้ามให้คะแนนคำแนะนำที่เป็นทฤษฎีทั่วไปแต่ปฏิบัติจริงในธนาคารไม่ได้"
}
```

## Suggest New Prompt

In [70]:
new_prompt_response = client.models.generate_content(model="gemini-3-pro-preview", 
                        contents=f"""
                        INSTRUCTION:
                        คุณคือ Agent ในการปรับปรุง prompt จากคำแนะนำ โดยประกอบด้วย prompt ของ scorer การให้คะแนน 3 ส่วน
                        1. reference - การให้คะแนนความถูกต้องของกฎหมายอ้างอิง โดยจำเป็นต้องบอกกฎหมายให้ถูกต้องและครบถ้วนตามที่มนุษย์ให้ไว้ เกณฑ์การให้คะแนนดังนี้
                            1.1 "อ้างอิงมาตรากฎหมายถูกต้องและครอบคลุมตามเฉลย": 1.0
                            1.2 "อ้างอิงมาตรากฎหมายไม่ถูกต้อง หรือไม่เกี่ยวข้อง": 0.0
                            1.3 "อ้างอิงมาตรากฎหมายถูกต้อง แต่ไม่ครอบคลุม มีมาตราสำคัญตกหล่น": 0.5

                        2. judgement - การให้คะแนนความสมเหตุสมผลของการวินิจฉัย โดยต้องสอดคล้องกับกฎหมายอ้างอิงที่ให้ไว้ และต้องมีเหตุผลสนับสนุนที่ชัดเจน เกณฑ์การให้คะแนนดังนี้
                        
                            2.1 "ตอบได้ถูกต้อง ชัดเจน ครอบคลุม": 1.0
                            2.2 "ไม่ถูกต้องตามเฉลย": 0.0
                            2.3 "ตอบได้ถูกต้อง แต่ไม่ครอบคลุม มีเนื้อหาสำคัญตกหล่น": 0.5
                        3. suggestion - การให้คะแนนความถูกต้องและความเหมาะสมของข้อสรุปและคำแนะนำ โดยต้องสอดคล้องกับกฎหมายอ้างอิงและการวินิจฉัยที่ให้ไว้ และต้องมีเหตุผลสนับสนุนที่ชัดเจน และต้องเป็นประโยชน์ต่อธนาคาร เกณฑ์การให้คะแนนดังนี้

                            3.1 "ตอบได้ถูกต้อง ชัดเจน ครอบคลุม ให้ข้อเสนอแนะที่เป็นไปได้จริง": 1.0
                            3.2 "ไม่ถูกต้องตามเฉลย": 0.0
                            3.3 "ตอบได้ถูกต้อง แต่ไม่ครอบคลุม มีเนื้อหาสำคัญตกหล่น": 0.5
                            
                        จงปรับปรุง prompt ของแต่ละ scorer โดยอิงจากคำแนะนำในการปรับปรุงที่ได้รับ 
                        
                        โดยอิงจากข้อมูลนี้: 
                        - current reference scorer prompt: {reference_prompt}
                        - current judgement scorer prompt: {judge_prompt}
                        - current suggestion scorer prompt: {suggestion_prompt}
                        - คำแนะนำในการปรับปรุง: {suggest_change_response.text}

                        OUTPUT: เพียง JSON เท่านั้น ที่มี key เป็น "reference", "judgement", "suggestion" และ value เป็น prompt ที่ถูกปรับปรุงใหม่สำหรับแต่ละ scorer
                        """,
                            
                config=types.GenerateContentConfig(
                    temperature=0
                ),)

In [71]:
# Extract JSON from the response text
json_text = new_prompt_response.text
start_idx = json_text.find('{')
end_idx = json_text.rfind('}') + 1
json_str = json_text[start_idx:end_idx]

# Parse and pretty print
new_prompts = json.loads(json_str)
print(json.dumps(new_prompts, indent=2, ensure_ascii=False))

{
  "reference": "คุณคือผู้เชี่ยวชาญทางกฎหมายที่ทำหน้าที่ประเมินคุณภาพคำตอบ และเลือกผลการประเมินตามตัวเลือกที่กำหนดให้\n\n# งานของคุณ\nให้คะแนนความถูกต้องของ **ข้อ 1 (มาตรากฎหมายที่เกี่ยวข้อง)** ในคำตอบ (OUTPUT) โดยเทียบกับเฉลย (EXPECTED) อย่างเคร่งครัดในระดับตัวอักษร (Verbatim)\n\n# รูปแบบข้อมูลเฉลย\nเฉลย (EXPECTED) อยู่ในรูปแบบ Markdown ที่แบ่งเป็นหัวข้อ:\n- `## 1. มาตรากฎหมายที่เกี่ยวข้อง` — มาตรากฎหมายและคำพิพากษาศาลฎีกาที่เกี่ยวข้อง (ใช้เป็นเฉลยหลักสำหรับการประเมินนี้)\n\n# เกณฑ์การประเมิน (Strict Verbatim & Formatting Check)\n1. **ความถูกต้องระดับตัวอักษร:** ตรวจสอบเทียบกับเฉลยแบบคำต่อคำ (Word-for-word comparison) ตัวบทกฎหมายต้อง **ครบถ้วนทุกตัวอักษร** \n   - ห้ามมีการตัดทอน (Truncation)\n   - ห้ามใช้เครื่องหมายละความ (...)\n   - ห้ามสรุปความเอง (Paraphrasing)\n   - ถ้อยคำเฉพาะทาง (Wording) เช่น 'คู่สมรส' vs 'สามีภริยา' ต้องตรงตามฉบับกฎหมายที่อ้างอิงในเฉลยเป๊ะๆ\n2. **ความถูกต้องของมาตรา:** เลขมาตราและชื่อกฎหมายต้องถูกต้องตรงกับเฉลย\n3. **สิ่งเจือปน (Noise):** ห้ามมีการอ้างอิงมาตราที่ไม่เกี่ยวข้อง (Irrelevant) ปะปนเข้ามา หากพบให้ถือว่าไม่ถูกต้องตามเกณฑ์\n4. **รูปแบบ (Formatting):** การจัดย่อหน้าและรูปแบบต้องสอดคล้องกับต้นฉบับกฎหมาย\n\n# ผลการประเมิน\nเลือกผลลัพธ์เพียงข้อเดียวที่ตรงที่สุด:\n- \"อ้างอิงมาตรากฎหมายถูกต้องและครอบคลุมตามเฉลย\": (1.0 คะแนน) เมื่อตัวบทครบถ้วนทุกตัวอักษร ตรงตามเฉลยแบบคำต่อคำ ไม่มีตัดทอน ไม่มีสรุปความ และไม่มีมาตราที่ไม่เกี่ยวข้องปะปน\n- \"อ้างอิงมาตรากฎหมายไม่ถูกต้อง หรือไม่เกี่ยวข้อง\": (0.0 คะแนน) เมื่ออ้างอิงผิดมาตรา, มีมาตราที่ไม่เกี่ยวข้องปะปนมา, หรือเนื้อหาตัวบทผิดเพี้ยนไปจากกฎหมายจริง\n- \"อ้างอิงมาตรากฎหมายถูกต้อง แต่ไม่ครอบคลุม มีมาตราสำคัญตกหล่น\": (0.5 คะแนน) เมื่อเลขมาตราถูก แต่ตัวบทมีการตัดทอน ใช้เครื่องหมาย (...) หรือสรุปความเอง หรือขาดวรรคตอนสำคัญ\n\n# ข้อมูล\nEXPECTED: {{expected}}\nOUTPUT: {{output}}",
  "judgement": "คุณคือผู้เชี่ยวชาญทางกฎหมายที่ทำหน้าที่ประเมินคุณภาพคำตอบ และเลือกผลการประเมินตามตัวเลือกที่กำหนดให้\n\n# งานของคุณ\nให้คะแนนความถูกต้องของ **ข้อ 2 (คำวินิจฉัย)** ในคำตอบ (OUTPUT) โดยเทียบกับเฉลย (EXPECTED) โดยเน้นความถูกต้องตามธงของเฉลย (Adherence to Expected Key) เป็นสำคัญ\n\n# รูปแบบข้อมูลเฉลย\n- `## 2. คำวินิจฉัย` — คำวินิจฉัยที่ถูกต้อง (ใช้เป็นเฉลยหลัก)\n\n# เกณฑ์การประเมิน (Adherence to Key & Banking Context)\n1. **ความถูกต้องของธงคำตอบ:** ตรวจสอบว่าผลทางกฎหมาย (เช่น โมฆะ, สมบูรณ์, ต้องรับผิด) ตรงกับเฉลยหรือไม่ **ห้ามให้คะแนนความสมเหตุสมผล หากข้อสรุปขัดแย้งกับเฉลย** แม้ว่าคำตอบจะดูมีตรรกะก็ตาม\n2. **ประเภทของหลักกฎหมาย (Legal Concept):** ตรวจสอบว่าใช้หลักกฎหมายตรงกันหรือไม่ (เช่น ต้องแยกแยะระหว่าง 'การแปลงหนี้ใหม่' กับ 'การขยายเวลา' ให้ถูกต้องตามเฉลย) หากวินิจฉัยด้วยหลักกฎหมายผิดประเภท ถือว่าผิดทันที\n3. **บริบทธนาคาร (Banking Context):** การวินิจฉัยต้องเป็นไปในเชิงระมัดระวัง (Conservative) ตามแนวปฏิบัติของธนาคารที่ระบุในเฉลย ห้ามยอมรับการตีความที่เสี่ยงหรือแตกต่างจากเฉลย\n4. **เลขฎีกา (Case Law):** หากเฉลยมีการระบุเลขคำพิพากษาศาลฎีกา คำตอบต้องอ้างอิงเลขฎีกาที่ตรงกันเท่านั้น หากอ้างอิงฎีกาอื่นที่ไม่เกี่ยวข้อง ให้ถือว่าเป็นข้อผิดพลาด\n\n# ผลการประเมิน\nเลือกผลลัพธ์เพียงข้อเดียวที่ตรงที่สุด:\n- \"ตอบได้ถูกต้อง ชัดเจน ครอบคลุม\": (1.0 คะแนน) ธงคำตอบถูก, หลักกฎหมายถูก, อ้างอิงฎีกาตรงกับเฉลย และวินิจฉัยในบริบทธนาคารได้ถูกต้อง\n- \"ไม่ถูกต้องตามเฉลย\": (0.0 คะแนน) ธงคำตอบผิด, ใช้หลักกฎหมายผิดประเภท, หรืออ้างอิงฎีกาผิด/ไม่เกี่ยวข้อง\n- \"ตอบได้ถูกต้อง แต่ไม่ครอบคลุม มีเนื้อหาสำคัญตกหล่น\": (0.5 คะแนน) ธงคำตอบถูก แต่ขาดรายละเอียดของเหตุผลสนับสนุน หรือขาดการอ้างอิงฎีกาที่ระบุในเฉลย\n\n# ข้อมูล\nEXPECTED: {{expected}}\nOUTPUT: {{output}}",
  "suggestion": "คุณคือผู้เชี่ยวชาญทางกฎหมายที่ทำหน้าที่ประเมินคุณภาพคำตอบ และเลือกผลการประเมินตามตัวเลือกที่กำหนดให้\n\n# งานของคุณ\nให้คะแนนความถูกต้องของ **ข้อ 3 (ข้อสรุปและข้อเสนอแนะ)** ในคำตอบ (OUTPUT) โดยเทียบกับเฉลย (EXPECTED) เน้นความเฉพาะเจาะจง (Specificity) และการนำไปใช้จริง\n\n# รูปแบบข้อมูลเฉลย\n- `## 3. ข้อสรุปและข้อเสนอแนะ` — ข้อสรุปและข้อเสนอแนะ (ใช้เป็นเฉลยหลัก)\n\n# เกณฑ์การประเมิน (Specificity & Practicality)\n1. **ความเฉพาะเจาะจง (Keywords):** ตรวจสอบหา Keywords สำคัญที่ปรากฏในเฉลย เช่น ตัวเลขวันเวลา (เช่น 'ภายใน 20 วัน'), ชื่อหน่วยงานเฉพาะ, ชื่อเอกสาร หรือขั้นตอนปฏิบัติที่ระบุไว้ชัดเจน หากคำตอบเขียนกว้างๆ (Generic) โดยไม่มี Keywords เหล่านี้ ให้หักคะแนน\n2. **ความสัมพันธ์กับคำวินิจฉัย:** หากคำวินิจฉัยในข้อ 2 ผิดพลาด ข้อเสนอแนะในข้อนี้ควรถูกพิจารณาว่าผิดด้วย เนื่องจากตั้งอยู่บนพื้นฐานที่ผิด\n3. **การปฏิบัติจริงในธนาคาร:** ตรวจสอบว่าข้อเสนอแนะขัดแย้งกับกฎระเบียบธนาคารในเฉลยหรือไม่ ต้องเป็นคำแนะนำที่ปฏิบัติได้จริง (Actionable) ไม่ใช่ทฤษฎีลอยๆ\n\n# ผลการประเมิน\nเลือกผลลัพธ์เพียงข้อเดียวที่ตรงที่สุด:\n- \"ตอบได้ถูกต้อง ชัดเจน ครอบคลุม ให้ข้อเสนอแนะที่เป็นไปได้จริง\": (1.0 คะแนน) มี Keywords ครบถ้วนตรงตามเฉลย, สอดคล้องกับกฎระเบียบธนาคาร และนำไปปฏิบัติได้จริง\n- \"ไม่ถูกต้องตามเฉลย\": (0.0 คะแนน) ขัดแย้งกับเฉลย, ขัดแย้งกับกฎระเบียบธนาคาร, หรือเป็นผลสืบเนื่องมาจากคำวินิจฉัยที่ผิดพลาด\n- \"ตอบได้ถูกต้อง แต่ไม่ครอบคลุม มีเนื้อหาสำคัญตกหล่น\": (0.5 คะแนน) ทิศทางถูกต้องแต่ตอบกว้างเกินไป (Generic) ขาด Keywords สำคัญ หรือขาดรายละเอียดขั้นตอนปฏิบัติ\n\n# ข้อมูล\nEXPECTED: {{expected}}\nOUTPUT: {{output}}"
}

In [ ]:
path = os.path.join("./skill_archive", "eval_scorer", EVAL_AI_MODEL, f"legal_reference_scorer_{NEW_EVAL_AI_PROMPT_VERSION}.md")
with open(path, "w", encoding="utf-8") as f:
    f.write(new_prompts["reference"])

    
path = os.path.join("./skill_archive", "eval_scorer", EVAL_AI_MODEL, f"legal_judgement_scorer_{NEW_EVAL_AI_PROMPT_VERSION}.md")
with open(path, "w", encoding="utf-8") as f:
    f.write(new_prompts["judgement"])

    
path = os.path.join("./skill_archive", "eval_scorer", EVAL_AI_MODEL, f"legal_suggestion_scorer_{NEW_EVAL_AI_PROMPT_VERSION}.md")
with open(path, "w", encoding="utf-8") as f:
    f.write(new_prompts["suggestion"])

## 4. Summary

All scorer reviews and prompt improvement suggestions are stored in `all_reviews` and `all_suggestions` for further use.